import type { Person } from "../types";

export const people: Person[] = [
  /* ---------------------------- Leadership ---------------------------- */
  {
    id: "bishnu-sharma",
    name: "Dr. Bishnu Prasad Sharma",
    role: "Principal",
    department: "Administration",
    qualification: "PhD Education (TU), MA English, MEd",
    experience: "28 years",
    subjects: ["Educational Leadership"],
    email: "principal@everestbutwal.edu.np",
    extension: "101",
    officeHours: "Sunday – Thursday, 10:30 – 12:30",
    bio: "Dr. Sharma has led Everest English since 2071 BS, having joined as an English teacher in 2055. His doctoral work examined English-medium instruction in Lumbini Province community schools, and he still teaches one Grade 12 English section each year on the grounds that a principal who stops teaching stops understanding the timetable. He chairs the scholarship selection committee.",
    joined: "2055 BS",
    leadership: true,
    rank: 1,
  },
  {
    id: "sarita-gurung",
    name: "Sarita Gurung",
    role: "Vice Principal · Academics",
    department: "Administration",
    qualification: "MSc Chemistry (TU), MEd Curriculum",
    experience: "21 years",
    subjects: ["Chemistry"],
    email: "vp.academics@everestbutwal.edu.np",
    extension: "102",
    officeHours: "Sunday – Friday, 11:00 – 13:00",
    bio: "Sarita Gurung owns the academic calendar, the examination schedule and the internal assessment audit. She rebuilt the school's practical assessment system in 2079 so that laboratory record books are checked termly rather than at the year's end, and she oversees the residential study hall programme.",
    joined: "2062 BS",
    leadership: true,
    rank: 2,
  },
  {
    id: "ramesh-thapa",
    name: "Ramesh Kumar Thapa",
    role: "Vice Principal · Administration",
    department: "Administration",
    qualification: "MBS (TU), BEd",
    experience: "19 years",
    subjects: ["Business Studies"],
    email: "vp.admin@everestbutwal.edu.np",
    extension: "103",
    officeHours: "Sunday – Friday, 10:00 – 12:00",
    bio: "Responsible for transport, facilities, safety and every notice that leaves the school. He introduced GPS tracking across the bus fleet in 2082 and publishes route timings each term. Parents with a logistics question are usually routed to his desk within the hour.",
    joined: "2064 BS",
    leadership: true,
    rank: 3,
  },
  {
    id: "anita-pandey",
    name: "Anita Pandey",
    role: "Coordinator · +2 Science",
    department: "Science",
    qualification: "MSc Physics (TU), BEd",
    experience: "16 years",
    subjects: ["Physics", "Mathematics"],
    email: "coord.science@everestbutwal.edu.np",
    extension: "210",
    officeHours: "Sunday – Friday, 09:15 – 10:45",
    bio: "Anita Pandey runs the Science stream end to end: admissions counselling, the practical timetable, and the six-paper IOE-pattern mock series she designed in 2080. She keeps a personal record of where every Grade 12 leaver landed, and will show it to any parent who asks.",
    joined: "2067 BS",
    leadership: true,
    rank: 4,
  },
  {
    id: "deepak-bhattarai",
    name: "Deepak Raj Bhattarai",
    role: "Coordinator · +2 Management",
    department: "Management",
    qualification: "MBA (PU), MBS (TU)",
    experience: "15 years",
    subjects: ["Accountancy", "Business Studies"],
    email: "coord.management@everestbutwal.edu.np",
    extension: "310",
    officeHours: "Sunday – Friday, 09:30 – 11:00",
    bio: "Deepak Bhattarai built the Management stream's case-based practicum and negotiates the Grade 12 internship placements with Butwal enterprises each year. He insists on hand-written ledgers before spreadsheets, which students complain about in Grade 11 and thank him for in Grade 12.",
    joined: "2068 BS",
    leadership: true,
    rank: 5,
  },
  {
    id: "kabita-shrestha",
    name: "Kabita Shrestha",
    role: "Coordinator · Secondary Level",
    department: "Administration",
    qualification: "MA Sociology (TU), BEd",
    experience: "17 years",
    subjects: ["Social Studies"],
    email: "coord.secondary@everestbutwal.edu.np",
    extension: "120",
    officeHours: "Sunday – Friday, 12:30 – 14:00",
    bio: "Kabita Shrestha oversees Grades 6 to 10, including SEE registration and the Grade 9 concentration counselling process. She introduced the tracked-evidence model that gives every Grade 8 family a written recommendation rather than a verbal one.",
    joined: "2066 BS",
    leadership: true,
    rank: 6,
  },

  /* ------------------------------ Faculty ----------------------------- */
  {
    id: "nabin-chaudhary",
    name: "Nabin Chaudhary",
    role: "Head of Physics",
    department: "Science",
    qualification: "MSc Physics (TU)",
    experience: "13 years",
    subjects: ["Physics", "Physics Practical"],
    email: "n.chaudhary@everestbutwal.edu.np",
    extension: "211",
    officeHours: "Sunday, Tuesday, Thursday · 11:30 – 12:30",
    bio: "Nabin Chaudhary teaches Grade 11 and 12 Physics and maintains the laboratory inventory. He runs the Thursday doubt clinic and has coached the school's entry to the provincial science exhibition for six consecutive years.",
    joined: "2070 BS",
  },
  {
    id: "sunita-adhikari",
    name: "Sunita Adhikari",
    role: "Head of Chemistry",
    department: "Science",
    qualification: "MSc Chemistry (TU), BEd",
    experience: "12 years",
    subjects: ["Chemistry", "Chemistry Practical"],
    email: "s.adhikari@everestbutwal.edu.np",
    extension: "212",
    officeHours: "Monday, Wednesday · 09:50 – 11:20",
    bio: "Sunita Adhikari handles Grade 11 and 12 Chemistry and the laboratory safety protocol. She rewrote the practical record book format in 2081 to match NEB internal marking exactly, a template now used by three other schools in Rupandehi.",
    joined: "2071 BS",
  },
  {
    id: "prakash-bhandari",
    name: "Prakash Bhandari",
    role: "Head of Biology",
    department: "Science",
    qualification: "MSc Botany (TU)",
    experience: "14 years",
    subjects: ["Biology", "Botany", "Zoology"],
    email: "p.bhandari@everestbutwal.edu.np",
    extension: "213",
    officeHours: "Sunday, Wednesday · 10:35 – 11:20",
    bio: "Prakash Bhandari runs the microscopy laboratory and curates the specimen collection. He organises the Grade 12 hospital observation day and prepares candidates for the MECEE mock series alongside Anita Pandey.",
    joined: "2069 BS",
  },
  {
    id: "aarati-kc",
    name: "Aarati KC",
    role: "Environmental Science Teacher & Wellbeing Lead",
    department: "Science",
    qualification: "MSc Environmental Science (PU), Diploma in Counselling",
    experience: "9 years",
    subjects: ["Environmental Science", "Life Skills"],
    email: "a.kc@everestbutwal.edu.np",
    extension: "140",
    officeHours: "Sunday – Friday · 13:00 – 14:00 drop-in",
    bio: "Aarati KC teaches Environmental Science and leads the wellbeing programme, including the no-appointment counselling drop-in hour. She is the faculty advisor to the Eco Club and maintains the botanical corner used in Biology practicals.",
    joined: "2074 BS",
  },
  {
    id: "hari-joshi",
    name: "Hari Prasad Joshi",
    role: "Head of Mathematics",
    department: "Mathematics",
    qualification: "MSc Mathematics (TU), MEd",
    experience: "22 years",
    subjects: ["Mathematics", "Optional Mathematics"],
    email: "h.joshi@everestbutwal.edu.np",
    extension: "220",
    officeHours: "Sunday – Thursday · 14:20 – 15:05",
    bio: "Hari Prasad Joshi has taught Optional Mathematics at Everest for over two decades and designed the ability-paced section model used in +2. He runs the Saturday problem-solving clinic in Falgun and Chaitra without charging for it.",
    joined: "2061 BS",
  },
  {
    id: "muna-karki",
    name: "Muna Karki",
    role: "Mathematics Teacher",
    department: "Mathematics",
    qualification: "MSc Mathematics (TU)",
    experience: "8 years",
    subjects: ["Mathematics", "Business Mathematics"],
    email: "m.karki@everestbutwal.edu.np",
    extension: "221",
    officeHours: "Monday, Wednesday, Friday · 13:35 – 14:20",
    bio: "Muna Karki teaches Grade 9 to 12 Mathematics and Business Mathematics for the Management stream. She runs the fortnightly mental mathematics ladder in the lower secondary years.",
    joined: "2075 BS",
  },
  {
    id: "rekha-subedi",
    name: "Rekha Subedi",
    role: "Head of English",
    department: "English",
    qualification: "MA English Literature (TU), BEd",
    experience: "15 years",
    subjects: ["Compulsory English", "Literature"],
    email: "r.subedi@everestbutwal.edu.np",
    extension: "230",
    officeHours: "Sunday, Tuesday · 12:50 – 13:35",
    bio: "Rekha Subedi leads the English department and edits the school literary magazine, Sagarmatha Patra. She built the long-form writing studio in the Language & Communication track and marks every 1,500-word essay herself.",
    joined: "2068 BS",
  },
  {
    id: "nirajan-poudel",
    name: "Nirajan Poudel",
    role: "English Teacher & Debate Coach",
    department: "English",
    qualification: "MA English (TU)",
    experience: "7 years",
    subjects: ["Compulsory English", "Public Speaking"],
    email: "n.poudel@everestbutwal.edu.np",
    extension: "231",
    officeHours: "Monday, Thursday · 14:20 – 15:05",
    bio: "Nirajan Poudel coaches the parliamentary debate squad, which has reached the provincial semi-final three years running. He teaches Grade 9 to 11 English and runs the termly debate ladder.",
    joined: "2076 BS",
  },
  {
    id: "gopal-basnet",
    name: "Gopal Bahadur Basnet",
    role: "Head of Nepali",
    department: "Nepali",
    qualification: "MA Nepali (TU), BEd",
    experience: "20 years",
    subjects: ["Compulsory Nepali", "Nepali Literature"],
    email: "g.basnet@everestbutwal.edu.np",
    extension: "240",
    officeHours: "Sunday – Wednesday · 11:30 – 12:15",
    bio: "Gopal Bahadur Basnet has taught Nepali at Everest since 2063 BS and leads the literary appreciation module in the Language & Communication track. He hosts the annual Kavita Sandhya poetry evening.",
    joined: "2063 BS",
  },
  {
    id: "laxmi-tiwari",
    name: "Laxmi Devi Tiwari",
    role: "Nepali Teacher",
    department: "Nepali",
    qualification: "MA Nepali (TU)",
    experience: "11 years",
    subjects: ["Compulsory Nepali", "Moral Education"],
    email: "l.tiwari@everestbutwal.edu.np",
    extension: "241",
    officeHours: "Tuesday, Thursday · 13:15 – 13:55",
    bio: "Laxmi Devi Tiwari teaches Nepali across the lower secondary years and coordinates Moral Education. She manages the Nepali section of the school library's acquisition list.",
    joined: "2072 BS",
  },
  {
    id: "sabin-rana",
    name: "Sabin Rana Magar",
    role: "Head of Computer Science",
    department: "Computer Science",
    qualification: "MSc CSIT (TU)",
    experience: "10 years",
    subjects: ["Computer Science", "Programming", "Robotics"],
    email: "s.rana@everestbutwal.edu.np",
    extension: "250",
    officeHours: "Sunday – Friday · 15:30 – 16:30 (lab open)",
    bio: "Sabin Rana Magar runs the computing and robotics laboratory and keeps it unlocked until half past four for club work. He supervises the Grade 12 Management capstone and the inter-school coding relay hosted on campus each Poush.",
    joined: "2073 BS",
  },
  {
    id: "prerana-sapkota",
    name: "Prerana Sapkota",
    role: "Computer Science Teacher",
    department: "Computer Science",
    qualification: "BSc CSIT (TU), MSc Information Systems (PU)",
    experience: "6 years",
    subjects: ["Computer Science", "Data & Spreadsheets"],
    email: "p.sapkota@everestbutwal.edu.np",
    extension: "251",
    officeHours: "Monday, Wednesday · 14:35 – 15:15",
    bio: "Prerana Sapkota teaches Computer Science in the secondary concentration and the spreadsheet modelling module for Management. She maintains the shared repository of solved practical problems handed down each year.",
    joined: "2077 BS",
  },
  {
    id: "bikash-kandel",
    name: "Bikash Kandel",
    role: "Head of Accountancy",
    department: "Management",
    qualification: "MBS (TU), CAP-II (ICAN)",
    experience: "13 years",
    subjects: ["Accountancy", "Financial Accounting"],
    email: "b.kandel@everestbutwal.edu.np",
    extension: "311",
    officeHours: "Sunday, Tuesday, Thursday · 09:20 – 10:05",
    bio: "Bikash Kandel teaches Accountancy in Grades 11 and 12 and marks the bookkeeping portfolio each semester. He prepares the small group of students who take the ICAN CAP-I examination directly after +2.",
    joined: "2070 BS",
  },
  {
    id: "sushma-rijal",
    name: "Sushma Rijal",
    role: "Economics Teacher",
    department: "Management",
    qualification: "MA Economics (TU)",
    experience: "9 years",
    subjects: ["Economics", "Business Studies"],
    email: "s.rijal@everestbutwal.edu.np",
    extension: "312",
    officeHours: "Monday, Wednesday · 10:05 – 10:50",
    bio: "Sushma Rijal teaches Economics across both +2 Management groups and runs the quarterly inter-section business simulation with Deepak Bhattarai. She arranges the Grade 10 cooperative field visit.",
    joined: "2074 BS",
  },
  {
    id: "krishna-yadav",
    name: "Krishna Gopal Yadav",
    role: "Head of Social Studies",
    department: "Social Studies",
    qualification: "MA History (TU), BEd",
    experience: "18 years",
    subjects: ["Social Studies", "Population & Environment"],
    email: "k.yadav@everestbutwal.edu.np",
    extension: "260",
    officeHours: "Sunday, Tuesday · 14:20 – 15:05",
    bio: "Krishna Gopal Yadav leads Social Studies and designed the Lumbini heritage project unit taken by every Grade 4 and 5 cohort. He also manages the school's SEE registration paperwork with Kabita Shrestha.",
    joined: "2065 BS",
  },
  {
    id: "tek-rai",
    name: "Tek Bahadur Rai",
    role: "Head of Physical Education",
    department: "Physical Education",
    qualification: "BPEd (TU), NSC Level-2 Coaching",
    experience: "16 years",
    subjects: ["Health & Physical Education", "Athletics"],
    email: "t.rai@everestbutwal.edu.np",
    extension: "270",
    officeHours: "Sunday – Friday · 06:00 – 07:00 (ground)",
    bio: "Tek Bahadur Rai runs the athletics ground, the covered court and the four-house competition structure. He schedules the inter-house meet in Shrawan on the argument that the ground drains well enough to risk it.",
    joined: "2067 BS",
  },
  {
    id: "sanjay-panthi",
    name: "Sanjay Panthi",
    role: "Science Teacher · Lower Secondary",
    department: "Science",
    qualification: "MSc Zoology (TU), BEd",
    experience: "8 years",
    subjects: ["Science & Technology", "STEM Track"],
    email: "s.panthi@everestbutwal.edu.np",
    extension: "214",
    officeHours: "Tuesday, Thursday · 12:35 – 13:15",
    bio: "Sanjay Panthi teaches Science in Grades 6 to 8 and runs the STEM Foundation Track project studio. He reviews every student build log with the +2 Science coordinator before exhibition entries are finalised.",
    joined: "2075 BS",
  },
  {
    id: "binita-thapa",
    name: "Binita Thapa Magar",
    role: "English Teacher · Primary",
    department: "English",
    qualification: "MA English (TU), Montessori Diploma",
    experience: "10 years",
    subjects: ["English", "Phonics"],
    email: "b.thapa@everestbutwal.edu.np",
    extension: "232",
    officeHours: "Sunday – Wednesday · 13:35 – 14:15",
    bio: "Binita Thapa Magar leads the phonics sequence in the Early Years and runs the daily reading intervention block in Grades 1 to 3. She trains new primary teachers on oral fluency assessment.",
    joined: "2073 BS",
  },
  {
    id: "nisha-baral",
    name: "Nisha Baral",
    role: "Admissions Officer",
    department: "Administration",
    qualification: "BBS (TU)",
    experience: "7 years",
    subjects: ["Admissions & Counselling"],
    email: "admissions@everestbutwal.edu.np",
    extension: "110",
    officeHours: "Sunday – Friday · 09:00 – 16:00",
    bio: "Nisha Baral is the first point of contact for every admission and scholarship enquiry. She maintains the applicant tracker and confirms every submitted scholarship file in writing within two working days.",
    joined: "2076 BS",
  },
  {
    id: "dinesh-gharti",
    name: "Dinesh Gharti",
    role: "Accounts & Services Officer",
    department: "Administration",
    qualification: "MBS (TU)",
    experience: "12 years",
    subjects: ["Accounts", "Fee & Scholarship Disbursement"],
    email: "accounts@everestbutwal.edu.np",
    extension: "111",
    officeHours: "Sunday – Friday · 09:30 – 15:30",
    bio: "Dinesh Gharti handles fee collection, scholarship disbursement and the dining hall contract. Fee adjustments for approved scholarship holders are applied at his desk before the term invoice is issued.",
    joined: "2071 BS",
  },
  {
    id: "manju-limbu",
    name: "Manju Limbu",
    role: "Librarian",
    department: "Administration",
    qualification: "MA Library & Information Science (TU)",
    experience: "11 years",
    subjects: ["Library & Information Skills"],
    email: "library@everestbutwal.edu.np",
    extension: "130",
    officeHours: "Sunday – Friday · 06:15 – 17:30",
    bio: "Manju Limbu catalogues the collection, staffs the reference desk through every period and keeps the waitlist for high-demand titles. She curates the NEB past-paper archive that goes back fourteen years.",
    joined: "2072 BS",
  },
];

export const leadership = people
  .filter((p) => p.leadership)
  .sort((a, b) => (a.rank ?? 99) - (b.rank ?? 99));

export const faculty = people.filter((p) => !p.leadership);

export const facultyDepartments = Array.from(
  new Set(people.map((p) => p.department)),
).sort();
