import type { Notice } from "#/types/website";

export type { Notice } from "#/types/website";

export const notices: Notice[] = [
  {
    id: "first-terminal-2083",
    ref: "EEBSS/2083/EXM/041",
    title: "First Terminal Examination 2083 — Routine and Examination Rules",
    category: "Examination",
    dateAd: "2026-09-04",
    dateBs: "Bhadra 19, 2083",
    audience: "All students · Grade 6 to Grade 12",
    issuedBy: "Sarita Gurung, Vice Principal (Academics)",
    summary: `The First Terminal Examination for the 2083 session begins on Ashwin 2 and runs to Ashwin 12. The full routine, seating arrangement and examination rules are published below and attached as a printable document.`,
    body: [
      `The First Terminal Examination for the academic session 2083 BS will be conducted from Ashwin 2 to Ashwin 12, 2083 (18 September to 28 September 2026) for all students of Grade 6 to Grade 12. Examinations for the +2 levels will be held in the morning shift and Grade 6 to 10 in the day shift, following the regular class timings.`,
      `Seating arrangements will be displayed on the notice board outside the examination hall two days before the first paper. Students must locate their seat number before the examination day; no seating queries will be entertained on the morning of a paper.`,
      `Admit cards will be distributed through class teachers from Bhadra 26. Students with outstanding dues from the previous term must clear them at the accounts desk before the admit card can be released. Scholarship holders whose fee adjustment is already recorded need take no action.`,
    ],
    bullets: [
      `Report to the examination hall fifteen minutes before the paper begins.`,
      `Admit card and school identity card are both compulsory for entry.`,
      `Only transparent geometry boxes and non-programmable calculators are permitted where the subject allows.`,
      `Mobile phones and smart watches are not permitted inside the hall under any circumstances.`,
      `Answer scripts will not be accepted after the final bell; plan your last ten minutes accordingly.`,
      `A student arriving more than thirty minutes late will not be admitted to that paper.`,
    ],
    table: {
      caption: "First Terminal Examination routine · Ashwin 2–12, 2083 BS",
      columns: [
        "Date (BS)",
        "Date (AD)",
        "Grade 9–10",
        "Grade 11–12 Science",
        "Grade 11–12 Management",
      ],
      rows: [
        ["Ashwin 2", "18 Sep 2026", "Compulsory English", "Compulsory English", "Compulsory English"],
        ["Ashwin 4", "20 Sep 2026", "Compulsory Mathematics", "Physics", "Accountancy"],
        ["Ashwin 6", "22 Sep 2026", "Science & Technology", "Chemistry", "Business Studies"],
        ["Ashwin 8", "24 Sep 2026", "Compulsory Nepali", "Mathematics / Biology", "Economics"],
        ["Ashwin 10", "26 Sep 2026", "Social Studies", "Computer Science", "Business Mathematics"],
        ["Ashwin 12", "28 Sep 2026", "Optional paper", "Compulsory Nepali", "Compulsory Nepali"],
      ],
    },
    attachments: [
      { name: "First-Terminal-Routine-2083.pdf", kind: "PDF", size: "218 KB" },
      { name: "Examination-Rules-2083.pdf", kind: "PDF", size: "96 KB" },
    ],
    pinned: true,
  },
  {
    id: "dashain-tihar-2083",
    ref: "EEBSS/2083/ADM/038",
    title: "Dashain and Tihar Vacation Schedule 2083",
    category: "Holiday",
    dateAd: "2026-09-02",
    dateBs: "Bhadra 17, 2083",
    audience: "All students, parents and staff",
    issuedBy: "Ramesh Kumar Thapa, Vice Principal (Administration)",
    summary: `The school will remain closed for the Dashain and Tihar festivals from Ashwin 24 to Kartik 12, 2083. Hostel closure, transport suspension and reopening arrangements are detailed below.`,
    body: [
      `The school will observe the annual Dashain and Tihar vacation from Ashwin 24 to Kartik 12, 2083 BS (10 October to 28 October 2026). Regular classes will resume on Kartik 13, 2083 (29 October 2026) for all levels, in the usual shifts.`,
      `The residential hostel will close at 12:00 noon on Ashwin 23 and reopen from 14:00 on Kartik 12. Parents and guardians are requested to complete departure formalities with the resident warden. Students unable to travel home must submit a written request to the Vice Principal (Academics) before Ashwin 18 so that skeleton catering and supervision can be arranged.`,
      `The school transport fleet will not operate during the vacation. Route timings for the reopening week will be published on this notice board on Kartik 10.`,
      `Holiday assignments will be shared by subject teachers before Ashwin 22 and are due on the first working day after reopening. Grade 12 students are reminded that the second mock series begins in Kartik and the holiday period is not free time.`,
    ],
    bullets: [
      `Vacation: Ashwin 24 – Kartik 12, 2083 BS.`,
      `Classes resume: Kartik 13, 2083 (29 October 2026).`,
      `Hostel closes Ashwin 23 at noon, reopens Kartik 12 at 14:00.`,
      `Transport suspended for the full vacation period.`,
      `Hostel stay-back requests due by Ashwin 18.`,
    ],
    attachments: [{ name: "Vacation-Notice-2083.pdf", kind: "PDF", size: "84 KB" }],
  },
  {
    id: "plus2-admission-phase2",
    ref: "EEBSS/2083/ADM/036",
    title: "+2 Science and Management Admission — Second Phase Now Open",
    category: "Admission",
    dateAd: "2026-08-31",
    dateBs: "Bhadra 15, 2083",
    audience: "SEE 2083 appeared and passed candidates",
    issuedBy: "Nisha Baral, Admissions Officer",
    summary: `Limited seats remain in the +2 Science Biology group and both Management groups. Second-phase applications close on Ashwin 8, 2083, and the entrance interview is scheduled for Ashwin 11.`,
    body: [
      `Following the completion of first-phase admissions, the following seats remain available for the academic session 2083: Science (Biology group) — 14 seats; Management (Accountancy & Finance group) — 21 seats; Management (Computer & Business Studies group) — 18 seats. The Science Physical group is now full and a waiting list is being maintained.`,
      `Candidates must submit the completed application form along with the SEE grade sheet, character certificate, transfer certificate, citizenship or birth certificate copy and four passport-size photographs. Forms are available at the admissions desk between 09:00 and 16:00 on any working day.`,
      `The second-phase entrance interview will be held on Ashwin 11, 2083 in the auditorium. Candidates applying under any scholarship scheme must indicate this on the application form itself; a scholarship claim cannot be added after the interview.`,
    ],
    bullets: [
      `Application deadline: Ashwin 8, 2083 (24 September 2026), 16:00.`,
      `Entrance interview: Ashwin 11, 2083, 08:00 onward, Auditorium.`,
      `Science Physical group is full — waiting list only.`,
      `Scholarship intent must be declared on the application form.`,
    ],
    attachments: [
      { name: "Plus2-Admission-Form-2083.pdf", kind: "PDF", size: "142 KB" },
      { name: "Fee-Structure-2083.pdf", kind: "PDF", size: "112 KB" },
    ],
  },
  {
    id: "chhatrabritti-open-2083",
    ref: "EEBSS/2083/SCH/012",
    title: "Chhatrabritti (Scholarship) Applications Open for Session 2083",
    category: "Scholarship",
    dateAd: "2026-08-28",
    dateBs: "Bhadra 12, 2083",
    audience: "All students and new applicants",
    issuedBy: "Dr. Bishnu Prasad Sharma, Principal",
    summary: `Nine scholarship schemes are open for the 2083 session, covering between 40 and 100 percent of tuition. Deadlines run from Ashwin through Poush; each scheme has its own criteria and document list.`,
    body: [
      `The scholarship selection committee invites applications for all nine schemes operating in the 2083 academic session. Together these cover 127 places across merit, need-based, government quota, sports, arts and community categories, with tuition relief ranging from forty to one hundred percent.`,
      `Every scheme has a separate deadline, criteria set and document checklist, all published on the Scholarships page of this site along with downloadable application forms and a printable document checklist. Applicants are strongly advised to read the eligibility conditions in full before submitting; incomplete files are returned rather than held.`,
      `Selection is made by the committee chaired by the Principal and is final. Results are communicated in writing to the address on the application form and simultaneously posted on this notice board. Students already holding a scholarship must submit the renewal declaration; continuation is not automatic.`,
    ],
    bullets: [
      `127 scholarship places across nine schemes.`,
      `Tuition relief between 40% and 100%.`,
      `Each scheme has its own deadline — the earliest closes in Ashwin.`,
      `Renewal declaration is compulsory for existing holders.`,
    ],
    attachments: [
      { name: "Scholarship-Guidelines-2083.pdf", kind: "PDF", size: "204 KB" },
      { name: "Scholarship-Application-Form.pdf", kind: "PDF", size: "128 KB" },
    ],
  },
  {
    id: "neb-grade11-registration",
    ref: "EEBSS/2083/EXM/034",
    title: "NEB Grade 11 Registration — Photograph and Document Submission",
    category: "Examination",
    dateAd: "2026-08-25",
    dateBs: "Bhadra 9, 2083",
    audience: "Grade 11 students · Science and Management",
    issuedBy: "Anita Pandey, Coordinator (+2 Science)",
    summary: `Grade 11 students must submit their NEB registration documents and photographs by Bhadra 22. Names and dates of birth must match the SEE grade sheet exactly — corrections after submission are not possible.`,
    body: [
      `Registration with the National Examinations Board for the Grade 11 cohort of session 2083 is now open. All students must submit the completed registration form, two copies of the SEE grade sheet, a copy of the character certificate and six passport-size photographs with a white background to their class teacher by Bhadra 22, 2083.`,
      `Students must verify that the spelling of their name, their parents' names, and the date of birth on the registration form match the SEE grade sheet character for character. The Board does not permit corrections after registration is processed, and a mismatch will follow the student through every certificate they receive.`,
      `Any student whose SEE grade sheet is under re-totalling or whose documents are incomplete must report to the coordinator's office in person before Bhadra 20.`,
    ],
    bullets: [
      `Submission deadline: Bhadra 22, 2083 (7 September 2026).`,
      `Six passport photographs, white background, name written on the reverse.`,
      `Details must match the SEE grade sheet exactly.`,
      `Document problems: report in person before Bhadra 20.`,
    ],
    attachments: [
      { name: "NEB-Grade11-Registration-Form.pdf", kind: "PDF", size: "156 KB" },
    ],
  },
  {
    id: "science-exhibition-2083",
    ref: "EEBSS/2083/EVT/029",
    title: "Everest Science Exhibition 2083 — Call for Project Proposals",
    category: "Event",
    dateAd: "2026-08-21",
    dateBs: "Bhadra 5, 2083",
    audience: "Grade 6 to Grade 12",
    issuedBy: "Nabin Chaudhary, Head of Physics",
    summary: `Project proposals for the fourteenth Everest Science Exhibition are invited until Ashwin 5. Working models, research posters and software projects are all eligible, in teams of up to three.`,
    body: [
      `The fourteenth Everest Science Exhibition will be held on Mangsir 8 and 9, 2083 in the auditorium and central courtyard. Entries are invited in four categories: working model, research poster, software or robotics project, and environmental study. Teams may have up to three members and must include a named faculty guide.`,
      `Proposals of not more than one page — stating the question, the method and the materials required — must be submitted to the Physics department by Ashwin 5, 2083. Accepted teams will be allocated a consumables budget from the laboratory fund and bench time in the relevant laboratory.`,
      `The three highest-placed entries will represent the school at the Rupandehi district exhibition in Poush. Students of the STEM Foundation Track are reminded that entry is compulsory rather than optional for them.`,
    ],
    bullets: [
      `Proposal deadline: Ashwin 5, 2083 (21 September 2026).`,
      `Exhibition dates: Mangsir 8–9, 2083.`,
      `Teams of up to three, with a named faculty guide.`,
      `Consumables budget provided to accepted teams.`,
      `Top three entries proceed to the district exhibition.`,
    ],
    attachments: [
      { name: "Exhibition-Proposal-Template.pdf", kind: "PDF", size: "72 KB" },
    ],
  },
  {
    id: "unit-test-results",
    ref: "EEBSS/2083/RES/025",
    title: "Unit Test Results Published — Grade 9 and Grade 10",
    category: "Result",
    dateAd: "2026-08-17",
    dateBs: "Bhadra 1, 2083",
    audience: "Grade 9 and Grade 10 students and parents",
    issuedBy: "Kabita Shrestha, Coordinator (Secondary Level)",
    summary: `Second unit test results for Grades 9 and 10 are now available with class teachers. Parents of students below the 40 percent threshold in any subject will be contacted individually for a support conversation.`,
    body: [
      `The results of the second unit test for Grade 9 and Grade 10 have been finalised and are available with the respective class teachers from today. Individual mark sheets will be sent home with students on Bhadra 3 and must be returned signed by a parent or guardian within three working days.`,
      `Students scoring below forty percent in any single subject will be enrolled in the subject support group that runs during the seventh period. This is not optional and does not carry an additional fee. Parents of these students will be telephoned by the class teacher during the coming week to agree a short plan.`,
      `Answer scripts may be reviewed in the presence of the subject teacher during their published office hours. Requests for re-totalling must be made within five working days of receiving the mark sheet.`,
    ],
    bullets: [
      `Mark sheets sent home: Bhadra 3, 2083.`,
      `Signed acknowledgement due within three working days.`,
      `Below 40% in any subject: automatic enrolment in the seventh-period support group.`,
      `Re-totalling requests: within five working days.`,
    ],
    attachments: [
      { name: "Unit-Test-2-Class-Analysis.pdf", kind: "PDF", size: "188 KB" },
    ],
  },
  {
    id: "athletics-meet-selection",
    ref: "EEBSS/2083/SPT/021",
    title: "Inter-House Athletics Meet — Team Selection Trials",
    category: "Sports",
    dateAd: "2026-08-12",
    dateBs: "Shrawan 27, 2083",
    audience: "All students · Grade 6 to Grade 12",
    issuedBy: "Tek Bahadur Rai, Head of Physical Education",
    summary: `Selection trials for the annual inter-house athletics meet will be held on the south ground from Shrawan 30 to Bhadra 2, before school in the morning session.`,
    body: [
      `Trials for the twenty-first inter-house athletics meet will be held on the south ground from Shrawan 30 to Bhadra 2, 2083, between 06:15 and 07:15 each morning. Events include 100 m, 200 m, 400 m, relay, long jump, high jump and shot put, in junior and senior categories for both boys and girls.`,
      `Students must register with their house captain before Shrawan 29 and report in sports uniform with proper footwear. Any student under medical restriction must present a note from the health centre before trialling.`,
      `The meet itself will be held on Bhadra 14 and 15 on the south ground. Sagarmatha, Annapurna, Dhaulagiri and Machhapuchhre houses will compete for the overall shield, which Annapurna currently holds.`,
    ],
    bullets: [
      `Trials: Shrawan 30 – Bhadra 2, 06:15 – 07:15, south ground.`,
      `Register with your house captain by Shrawan 29.`,
      `Sports uniform and proper footwear compulsory.`,
      `Meet dates: Bhadra 14–15, 2083.`,
    ],
    attachments: [
      { name: "Athletics-Meet-Events-List.pdf", kind: "PDF", size: "68 KB" },
    ],
  },
  {
    id: "ptm-plus2",
    ref: "EEBSS/2083/GEN/019",
    title: "Parent–Teacher Meeting — Grade 11 and Grade 12",
    category: "General",
    dateAd: "2026-08-07",
    dateBs: "Shrawan 22, 2083",
    audience: "Parents and guardians · Grade 11 and 12",
    issuedBy: "Sarita Gurung, Vice Principal (Academics)",
    summary: `The first parent-teacher meeting of the session for the +2 levels will be held on Shrawan 31 in the auditorium, with subject-wise desks from 09:00 to 12:30.`,
    body: [
      `The first parent-teacher meeting for the +2 levels of session 2083 will be held on Shrawan 31, 2083 (16 August 2026) in the auditorium and adjacent classrooms. Subject teachers will be available at named desks between 09:00 and 12:30; no appointment is required.`,
      `The Principal will address parents briefly at 09:15, followed by a short presentation from the stream coordinators covering the internal assessment structure, the mock examination calendar and entrance preparation timelines.`,
      `Parents are requested to bring the student's progress folder. Students are encouraged but not required to attend with their parents; for Grade 12 families, coordinators have found the conversation considerably more useful when the student is present.`,
    ],
    bullets: [
      `Date: Shrawan 31, 2083, 09:00 – 12:30.`,
      `Principal's address at 09:15, coordinator briefings from 09:35.`,
      `No appointment needed — subject desks are open.`,
      `Please bring the student progress folder.`,
    ],
    attachments: [{ name: "PTM-Desk-Map-Plus2.pdf", kind: "PDF", size: "58 KB" }],
  },
  {
    id: "library-renewal",
    ref: "EEBSS/2083/GEN/016",
    title: "Library Membership Renewal and New Arrivals",
    category: "General",
    dateAd: "2026-08-02",
    dateBs: "Shrawan 17, 2083",
    audience: "All students and staff",
    issuedBy: "Manju Limbu, Librarian",
    summary: `Library cards for session 2083 must be renewed at the reference desk by Bhadra 5. Four hundred and twelve new titles have been catalogued, including a refreshed NEB past-paper set.`,
    body: [
      `Library membership for the academic session 2083 is now open for renewal at the reference desk. Students must bring their previous card and one photograph; renewal takes under five minutes and can be done during any free period. Borrowing privileges for un-renewed cards will be suspended after Bhadra 5.`,
      `Four hundred and twelve new titles have been catalogued this session, including sixty-eight Nepali literature volumes, a complete refreshed NEB past-paper set for both streams, and a new reference section on entrance examination preparation. The complete accession list is posted beside the reference desk and attached below.`,
      `A reminder that the silent reading hall operates on a strict no-conversation basis and that the forty carrels cannot be reserved in advance — they are first come, first served, and they fill by 15:30 most days.`,
    ],
    bullets: [
      `Renewal deadline: Bhadra 5, 2083.`,
      `Bring the previous card and one photograph.`,
      `412 new titles catalogued, including a refreshed past-paper set.`,
      `Silent hall carrels cannot be reserved — first come, first served.`,
    ],
    attachments: [
      { name: "Library-Accession-List-2083.pdf", kind: "PDF", size: "244 KB" },
    ],
  },
  {
    id: "revised-routine-plus2",
    ref: "EEBSS/2083/GEN/014",
    title: "Revised Morning Shift Class Routine for +2 Levels",
    category: "General",
    dateAd: "2026-07-28",
    dateBs: "Shrawan 12, 2083",
    audience: "Grade 11 and Grade 12 students and staff",
    issuedBy: "Anita Pandey & Deepak Raj Bhattarai, Stream Coordinators",
    summary: `The revised morning shift routine takes effect from Shrawan 12. Science classes now begin at 06:30 and Management at 06:45, with practical periods consolidated to the last slot of the day.`,
    body: [
      `The revised class routine for both +2 streams takes effect from today, Shrawan 12, 2083. Science classes will now begin at 06:30 and conclude at 11:20; Management classes begin at 06:45 and conclude at 11:35. The change consolidates all practical and studio periods into the final slot of the day so that laboratory sessions are not interrupted by a bell.`,
      `The tiffin break has been shortened by five minutes for both streams to accommodate the consolidation. The full revised routine for each stream is published on the Courses page of this site with a printable version available for download.`,
      `Students travelling by school bus should note the corresponding pick-up time change of ten minutes earlier on routes 3, 5 and 7. Revised route timings are available from the transport bay at Gate 2.`,
    ],
    bullets: [
      `Effective from Shrawan 12, 2083.`,
      `Science: 06:30 – 11:20. Management: 06:45 – 11:35.`,
      `Practical and studio periods moved to the final slot.`,
      `Routes 3, 5 and 7 pick up ten minutes earlier.`,
    ],
    attachments: [
      { name: "Revised-Routine-Plus2-2083.pdf", kind: "PDF", size: "134 KB" },
    ],
  },
  {
    id: "monsoon-advisory",
    ref: "EEBSS/2083/GEN/011",
    title: "Monsoon Safety Advisory and Transport Timing Change",
    category: "General",
    dateAd: "2026-07-22",
    dateBs: "Shrawan 6, 2083",
    audience: "All students, parents and staff",
    issuedBy: "Ramesh Kumar Thapa, Vice Principal (Administration)",
    summary: `Bus routes crossing the Tinau corridor will run fifteen minutes earlier through Shrawan and Bhadra. Any weather closure will be announced by 06:00 on this notice board.`,
    body: [
      `With the monsoon now established, routes 2, 4 and 6 which cross the Tinau corridor will depart fifteen minutes earlier than the published timing for the duration of Shrawan and Bhadra. Parents on these routes are requested to have students ready at the stop accordingly.`,
      `In the event of a weather-related closure, the decision will be taken and announced by 06:00 on this notice board and through class group messages. Parents are requested not to telephone the school office before that time, as the decision depends on the early-morning district advisory.`,
      `Students are reminded to carry a raincoat rather than an umbrella on bus routes, to keep textbooks in a plastic sleeve inside the bag, and to avoid the south ground and the courtyard during heavy rain. The covered court remains available for all break-time activity.`,
    ],
    bullets: [
      `Routes 2, 4 and 6: fifteen minutes earlier through Shrawan and Bhadra.`,
      `Weather closure announced by 06:00, not before.`,
      `Raincoats preferred over umbrellas on bus routes.`,
      `Covered court available during rain.`,
    ],
    attachments: [{ name: "Monsoon-Route-Timings.pdf", kind: "PDF", size: "76 KB" }],
  },
  {
    id: "see-felicitation",
    ref: "EEBSS/2083/EVT/008",
    title: "SEE 2083 Result — Toppers Felicitation Programme",
    category: "Event",
    dateAd: "2026-07-16",
    dateBs: "Ashadh 32, 2083",
    audience: "SEE 2083 batch, parents and all students",
    issuedBy: "Dr. Bishnu Prasad Sharma, Principal",
    summary: `The school recorded a 100 percent pass rate in SEE 2083 with nineteen students securing GPA above 3.60. A felicitation programme will be held on Shrawan 8 in the auditorium.`,
    body: [
      `The Secondary Education Examination results for 2083 have been published by the National Examinations Board. Everest English Boarding Secondary School recorded a hundred percent pass rate across the batch of 138 candidates, with nineteen students securing a grade point average above 3.60 and a further forty-seven above 3.20.`,
      `A felicitation programme for the outgoing batch will be held on Shrawan 8, 2083 at 11:00 in the auditorium. Parents of all SEE candidates are warmly invited. Certificates, the school medal and the annual academic shield will be presented at the programme.`,
      `Candidates intending to continue into the +2 programme at Everest should note that the first-phase admission window closes on Shrawan 15 and that internal candidates are counted within the same seat allocation as external applicants.`,
    ],
    bullets: [
      `100% pass rate across 138 candidates.`,
      `19 students above GPA 3.60; 47 above 3.20.`,
      `Felicitation: Shrawan 8, 2083, 11:00, Auditorium.`,
      `First-phase +2 admission closes Shrawan 15.`,
    ],
    attachments: [
      { name: "SEE-2083-Result-Summary.pdf", kind: "PDF", size: "162 KB" },
    ],
  },
  {
    id: "uniform-id-distribution",
    ref: "EEBSS/2083/GEN/006",
    title: "School Uniform and Identity Card Distribution Schedule",
    category: "General",
    dateAd: "2026-07-08",
    dateBs: "Ashadh 24, 2083",
    audience: "All students · new and continuing",
    issuedBy: "Dinesh Gharti, Accounts & Services Officer",
    summary: `Uniform sets and identity cards for session 2083 will be distributed level by level from Ashadh 28 to Shrawan 4 at the services counter beside the accounts office.`,
    body: [
      `Uniform sets and identity cards for the academic session 2083 will be distributed at the services counter beside the accounts office according to the schedule below. Students should collect in person; a parent may collect on presentation of the fee receipt.`,
      `Two full sets of the daily uniform and one sports set are included in the annual uniform charge already reflected in the term invoice. Winter items will be distributed separately in Kartik. Any sizing exchange must be raised within seven days of collection and the item must be unworn.`,
      `Identity cards are issued once per session. A replacement card costs Rs 250 and takes three working days. Students are reminded that the identity card is compulsory for examination hall entry, library borrowing and bus boarding.`,
    ],
    bullets: [
      `Ashadh 28 – 29: Grade 11 and 12.`,
      `Ashadh 30 – 32: Grade 9 and 10.`,
      `Shrawan 1 – 2: Grade 6 to 8.`,
      `Shrawan 3 – 4: Nursery to Grade 5.`,
      `Sizing exchange within seven days, unworn only.`,
    ],
    attachments: [
      { name: "Uniform-Distribution-Schedule.pdf", kind: "PDF", size: "62 KB" },
    ],
  },
  {
    id: "government-quota-notice",
    ref: "EEBSS/2083/SCH/004",
    title: "Free Studentship Under Government Quota — Notice to Applicants",
    category: "Scholarship",
    dateAd: "2026-06-30",
    dateBs: "Ashadh 16, 2083",
    audience: "Prospective and continuing students",
    issuedBy: "Dr. Bishnu Prasad Sharma, Principal",
    summary: `Thirty-three free studentship places are reserved under the government quota for session 2083, allocated in accordance with Ministry of Education directives across the prescribed categories.`,
    body: [
      `In accordance with the directives of the Ministry of Education, Science and Technology, thirty-three free studentship places are reserved at this institution for the academic session 2083. These places carry a full waiver of tuition and examination fees and are allocated across the categories prescribed by the directive, including students from Dalit and marginalised communities, students with disability, children of martyrs and conflict victims, and students from families below the recognised income threshold.`,
      `Applications must be submitted on the prescribed form together with the supporting documents listed in the guidelines. Income and category declarations must be attested by the relevant ward office. The committee verifies every declaration and reserves the right to conduct a home visit.`,
      `The allocation is published in full — with names and categories — on the notice board and submitted to the District Education Coordination Unit as required. Any complaint regarding the allocation may be filed in writing with the Principal within fifteen days of publication.`,
    ],
    bullets: [
      `33 places, full tuition and examination fee waiver.`,
      `Ward-office attestation required on income and category declarations.`,
      `Committee may conduct verification home visits.`,
      `Allocation published publicly; complaints accepted within fifteen days.`,
    ],
    attachments: [
      { name: "Government-Quota-Guidelines.pdf", kind: "PDF", size: "196 KB" },
      { name: "Free-Studentship-Form.pdf", kind: "PDF", size: "118 KB" },
    ],
  },
  {
    id: "session-begins-2083",
    ref: "EEBSS/2083/ADM/001",
    title: "Academic Session 2083 Begins — Orientation Programme",
    category: "Admission",
    dateAd: "2026-06-20",
    dateBs: "Ashadh 6, 2083",
    audience: "All students, parents and staff",
    issuedBy: "Sarita Gurung, Vice Principal (Academics)",
    summary: `The 2083 academic session opens on Ashadh 10 with a level-wise orientation. New students and their parents should attend the session for their level in the auditorium.`,
    body: [
      `The academic session 2083 BS will formally begin on Ashadh 10, 2083 (24 June 2026). Regular classes for all levels start on Ashadh 12 following the routine that will be posted on the notice board and on the Courses page of this site.`,
      `Level-wise orientation for new students and their parents will be held in the auditorium: Nursery to Grade 5 on Ashadh 10 at 09:00, Grade 6 to 10 on Ashadh 10 at 11:30, and Grade 11 and 12 on Ashadh 11 at 08:00. Class teacher allocation, house assignment and the term calendar will all be shared at orientation.`,
      `Textbook sets are available from the services counter from Ashadh 8. Bus route confirmations for the new session have been sent to registered numbers; parents who have not received a confirmation should contact the transport bay at Gate 2 before Ashadh 9.`,
    ],
    bullets: [
      `Session opens Ashadh 10; classes begin Ashadh 12.`,
      `Orientation: Nursery to Grade 5 at 09:00, Grade 6 to 10 at 11:30 on Ashadh 10.`,
      `Grade 11 and 12 orientation: Ashadh 11 at 08:00.`,
      `Textbook sets available from Ashadh 8.`,
    ],
    attachments: [
      { name: "Academic-Calendar-2083.pdf", kind: "PDF", size: "174 KB" },
    ],
  },
];

export const noticeCategories = Array.from(
  new Set(notices.map((n) => n.category)),
).sort();

export const pinnedNotice = notices.find((n) => n.pinned) ?? notices[0];
