import type { Scholarship } from "../types";

export const scholarships: Scholarship[] = [
  {
    id: "everest-merit",
    ref: "SCH/2083/MER/01",
    name: "Everest Merit Chhatrabritti",
    nepaliName: "एभरेस्ट प्रतिभा छात्रवृत्ति",
    category: "Merit",
    coverage: 100,
    award: "Full tuition, examination and laboratory fees for two years",
    amountNpr: 172800,
    seats: 12,
    deadlineAd: "2026-10-05",
    deadlineBs: "Ashwin 19, 2083",
    appliesTo: "+2 Science and +2 Management · Grade 11 entry",
    summary: `The school's flagship award for the twelve strongest SEE candidates entering +2, renewable into Grade 12 on performance.`,
    description: `The Merit Chhatrabritti is decided almost entirely on the SEE grade sheet, with a written test and interview used only to separate closely placed candidates. It covers tuition, examination and laboratory fees in full for both years of the +2 programme and carries no bond or service condition. Twelve places are divided as seven Science and five Management.`,
    eligibility: [
      {
        id: "gpa",
        label: "SEE GPA of 3.60 or above",
        detail: "Computed on the full eight-subject grade sheet, not a subject subset.",
      },
      {
        id: "core",
        label: "Minimum A grade in Mathematics, Science and English",
        detail: "All three core subjects must independently meet the threshold.",
      },
      {
        id: "first-attempt",
        label: "SEE cleared in the first attempt",
        detail: "Candidates who sat a supplementary or re-examination are not eligible for this scheme.",
      },
      {
        id: "admission",
        label: "Confirmed admission to Grade 11 at this institution",
        detail: "A provisional admission receipt is acceptable at the point of application.",
      },
      {
        id: "no-other",
        label: "Not holding another full-tuition scholarship",
        detail: "This award cannot be combined with the Government Free Studentship quota.",
      },
    ],
    benefits: [
      "100% tuition waiver for Grade 11 and Grade 12",
      "Full waiver of examination and laboratory fees",
      "Complimentary textbook and lab manual set each year",
      "Priority allocation in the +2 mock examination series",
      "Named mention on the annual academic shield",
    ],
    documents: [
      "Completed scholarship application form",
      "Original SEE grade sheet and two attested copies",
      "Character certificate from the previous school",
      "Citizenship certificate or birth registration copy",
      "Four passport-size photographs, white background",
      "Provisional admission receipt for Grade 11",
    ],
    process: [
      "Collect or download the application form and complete it in full",
      "Submit the file at the admissions desk and collect a dated receipt",
      "Sit the shortlisting written test if called (Ashwin 24)",
      "Attend the committee interview (Ashwin 26)",
      "Receive the written decision within seven working days",
    ],
    renewal: `Continues into Grade 12 provided the holder maintains a Grade 11 GPA of 3.40 or above with no subject below a B grade, and attendance of at least 85 percent.`,
    contact: "Nisha Baral, Admissions Officer · admissions@everestbutwal.edu.np · Ext. 110",
    spotlight: true,
  },
  {
    id: "see-distinction",
    ref: "SCH/2083/MER/02",
    name: "SEE Distinction Scholarship",
    nepaliName: "एस.ई.ई. विशिष्ट श्रेणी छात्रवृत्ति",
    category: "Merit",
    coverage: 75,
    award: "75% tuition waiver for the first year, renewable",
    amountNpr: 64800,
    seats: 20,
    deadlineAd: "2026-09-28",
    deadlineBs: "Ashwin 12, 2083",
    appliesTo: "+2 Science and +2 Management · Grade 11 entry",
    summary: `A broader merit award for strong SEE candidates who fall just below the Merit Chhatrabritti threshold.`,
    description: `The Distinction Scholarship exists so that the merit cliff is not so steep. It covers three quarters of tuition for Grade 11 and is renewed into Grade 12 on the same performance condition. Twenty places are available and allocation is strictly in descending order of SEE grade point average.`,
    eligibility: [
      {
        id: "gpa",
        label: "SEE GPA between 3.20 and 3.59",
        detail: "Candidates at 3.60 and above should apply to the Merit Chhatrabritti instead.",
      },
      {
        id: "core",
        label: "Minimum B+ grade in Mathematics and Science",
        detail: "English must be at least a B grade.",
      },
      {
        id: "first-attempt",
        label: "SEE cleared in the first attempt",
        detail: "Supplementary candidates are not eligible.",
      },
      {
        id: "admission",
        label: "Confirmed or provisional Grade 11 admission",
        detail: "Applies to both the Science and Management streams.",
      },
    ],
    benefits: [
      "75% tuition waiver for Grade 11",
      "Renewable at the same rate for Grade 12 on performance",
      "Complimentary lab manual set for Science candidates",
      "Free access to the +2 mock examination series",
    ],
    documents: [
      "Completed scholarship application form",
      "SEE grade sheet with two attested copies",
      "Character certificate",
      "Citizenship certificate or birth registration copy",
      "Three passport-size photographs",
    ],
    process: [
      "Submit the completed form at the admissions desk",
      "Collect the dated acknowledgement receipt",
      "Await the merit list publication on Ashwin 18",
      "Confirm acceptance in writing within five working days",
    ],
    renewal: `Renewed for Grade 12 if the holder maintains a Grade 11 GPA of 3.00 or above and attendance of at least 80 percent.`,
    contact: "Nisha Baral, Admissions Officer · admissions@everestbutwal.edu.np · Ext. 110",
  },
  {
    id: "government-quota",
    ref: "SCH/2083/GOV/03",
    name: "Government Free Studentship Quota",
    nepaliName: "सरकारी नि:शुल्क छात्रवृत्ति कोटा",
    category: "Government",
    coverage: 100,
    award: "Full waiver of tuition and examination fees",
    amountNpr: 148000,
    seats: 33,
    deadlineAd: "2026-11-10",
    deadlineBs: "Kartik 24, 2083",
    appliesTo: "All levels · Grade 1 to Grade 12",
    summary: `The statutory free studentship quota allocated under Ministry of Education directives, published openly each session.`,
    description: `Every institution of this category is required to reserve free studentship places, and this school allocates thirty-three across all levels. Allocation follows the categories set out in the Ministry directive and the full list — names and categories — is published on the notice board and filed with the District Education Coordination Unit. Every declaration is verified, and the committee may conduct a home visit.`,
    eligibility: [
      {
        id: "category",
        label: "Falls within a prescribed directive category",
        detail: "Dalit or marginalised community, student with disability, child of a martyr or conflict victim, or family below the recognised income threshold.",
      },
      {
        id: "attestation",
        label: "Ward-office attested category and income declaration",
        detail: "Self-declarations without ward attestation cannot be processed.",
      },
      {
        id: "residency",
        label: "Resident within Rupandehi district",
        detail: "Verified against the ward recommendation letter.",
      },
      {
        id: "single-claim",
        label: "No other institutional scholarship held",
        detail: "This quota cannot be combined with the Merit or Distinction awards.",
      },
      {
        id: "attendance",
        label: "Attendance of 75 percent to retain the place",
        detail: "Reviewed at the end of each term.",
      },
    ],
    benefits: [
      "100% tuition fee waiver",
      "Full examination and board fee waiver",
      "Free textbook set from the school library stock",
      "Uniform grant of Rs 6,000 in the first year",
      "Free access to all support and clinic sessions",
    ],
    documents: [
      "Prescribed free studentship application form",
      "Ward-office recommendation and income declaration",
      "Category certificate as applicable",
      "Previous academic transcript or transfer certificate",
      "Citizenship or birth registration copy of student and guardian",
      "Two passport-size photographs",
    ],
    process: [
      "Obtain the ward-office recommendation and income declaration first",
      "Submit the completed prescribed form with all attachments",
      "Cooperate with committee verification, including a possible home visit",
      "Check the publicly posted allocation list on Mangsir 10",
      "File any written complaint within fifteen days of publication",
    ],
    renewal: `Continues year to year as long as the category conditions still apply and attendance remains at or above 75 percent. Re-declaration is required each session.`,
    contact: "Dinesh Gharti, Accounts & Services Officer · accounts@everestbutwal.edu.np · Ext. 111",
    spotlight: true,
  },
  {
    id: "girls-education",
    ref: "SCH/2083/NED/04",
    name: "Lumbini Girls' Education Grant",
    nepaliName: "लुम्बिनी छात्रा शिक्षा अनुदान",
    category: "Need-based",
    coverage: 60,
    award: "60% tuition waiver plus an annual materials grant",
    amountNpr: 58400,
    seats: 15,
    deadlineAd: "2026-10-20",
    deadlineBs: "Kartik 3, 2083",
    appliesTo: "Grade 9 to Grade 12 · female students",
    summary: `Support for girls from low-income households in Rupandehi and neighbouring districts to complete secondary and +2 education.`,
    description: `This grant exists because the drop-off in female enrolment between Grade 8 and Grade 11 is the sharpest transition in the district's figures. It combines a sixty percent tuition waiver with an annual materials grant covering books, stationery and uniform, and holders are paired with a female faculty mentor for the duration of the award.`,
    eligibility: [
      {
        id: "gender",
        label: "Female student entering or continuing Grade 9 to 12",
        detail: "Open to both new applicants and continuing students.",
      },
      {
        id: "income",
        label: "Annual household income below Rs 400,000",
        detail: "Supported by a ward-office income declaration.",
      },
      {
        id: "academic",
        label: "Minimum GPA 2.40 in the last completed year",
        detail: "A lower GPA may be considered where the committee sees clear circumstance.",
      },
      {
        id: "district",
        label: "Resident of Rupandehi, Nawalparasi, Kapilvastu or Palpa",
        detail: "Hostel residents from these districts are eligible.",
      },
    ],
    benefits: [
      "60% tuition waiver, renewable annually",
      "Annual materials grant of Rs 12,000 for books, stationery and uniform",
      "Paired female faculty mentor for the award period",
      "Priority hostel allocation for out-of-city holders",
      "Free enrolment in all support and clinic sessions",
    ],
    documents: [
      "Completed application form",
      "Ward-office income declaration",
      "Last completed academic transcript",
      "Guardian's citizenship copy and student's birth registration",
      "Two passport-size photographs",
    ],
    process: [
      "Submit the application with the income declaration attached",
      "Attend a short interview with the committee's female members",
      "Await the written decision by Kartik 18",
      "Meet your assigned mentor in the first week of the award",
    ],
    renewal: `Renewed annually on continued income eligibility, a GPA of 2.20 or above, and attendance of at least 80 percent.`,
    contact: "Sarita Gurung, Vice Principal (Academics) · vp.academics@everestbutwal.edu.np · Ext. 102",
  },
  {
    id: "community-support",
    ref: "SCH/2083/COM/05",
    name: "Dalit and Marginalised Community Support",
    nepaliName: "दलित तथा सीमान्तकृत समुदाय सहयोग छात्रवृत्ति",
    category: "Community",
    coverage: 100,
    award: "Full tuition waiver with a monthly transport and meal stipend",
    amountNpr: 164000,
    seats: 10,
    deadlineAd: "2026-11-25",
    deadlineBs: "Mangsir 9, 2083",
    appliesTo: "Grade 6 to Grade 12",
    summary: `An institutional award over and above the government quota, adding a stipend because tuition alone is rarely the whole barrier.`,
    description: `The committee found that students admitted on a full tuition waiver were still dropping out over transport and meal costs. This award therefore pairs a hundred percent tuition waiver with a monthly stipend of Rs 3,000 towards bus fare and the dining hall lunch service. Ten places are available across Grades 6 to 12.`,
    eligibility: [
      {
        id: "community",
        label: "Belongs to a Dalit or officially marginalised community",
        detail: "Evidenced by the ward-office community certificate.",
      },
      {
        id: "income",
        label: "Annual household income below Rs 350,000",
        detail: "Ward-office attested declaration required.",
      },
      {
        id: "academic",
        label: "Passed the previous grade",
        detail: "No minimum GPA is applied to this scheme by design.",
      },
      {
        id: "not-gov",
        label: "Not already holding a government quota place",
        detail: "Applicants not selected in the quota are automatically considered here.",
      },
    ],
    benefits: [
      "100% tuition fee waiver",
      "Monthly stipend of Rs 3,000 for transport and lunch",
      "Free textbook, stationery and uniform set",
      "Examination and board fee waiver",
      "Assigned faculty mentor and termly review conversation",
    ],
    documents: [
      "Completed application form",
      "Ward-office community certificate",
      "Ward-office income declaration",
      "Previous grade transcript or transfer certificate",
      "Guardian's citizenship copy",
      "Two passport-size photographs",
    ],
    process: [
      "Submit the form with community and income certificates",
      "Committee verification, which may include a home visit",
      "Written decision issued by Mangsir 22",
      "Stipend disbursement begins from the following month at the accounts desk",
    ],
    renewal: `Continues year to year on passing the grade and maintaining 75 percent attendance. Re-declaration of income is required each session.`,
    contact: "Dr. Bishnu Prasad Sharma, Principal · principal@everestbutwal.edu.np · Ext. 101",
  },
  {
    id: "sports-excellence",
    ref: "SCH/2083/SPT/06",
    name: "Everest Sports Excellence Award",
    nepaliName: "एभरेस्ट खेलकुद उत्कृष्टता छात्रवृत्ति",
    category: "Sports",
    coverage: 50,
    award: "50% tuition waiver plus kit and travel support",
    amountNpr: 48600,
    seats: 8,
    deadlineAd: "2026-12-05",
    deadlineBs: "Mangsir 19, 2083",
    appliesTo: "Grade 9 to Grade 12",
    summary: `For students competing at district level or above, with a timetable adjustment built into the award rather than negotiated later.`,
    description: `Athletes who train seriously lose class time, and pretending otherwise is how sports scholarships fail. This award carries a formal timetable accommodation: holders get a documented catch-up arrangement with each subject teacher, plus kit and travel support for representative fixtures. Selection is by trial with the Head of Physical Education and a district association representative.`,
    eligibility: [
      {
        id: "level",
        label: "Represented at district level or above in a recognised sport",
        detail: "Certificate from the district or provincial sports association required.",
      },
      {
        id: "trial",
        label: "Cleared the school selection trial",
        detail: "Held on Mangsir 14 on the south ground.",
      },
      {
        id: "academic",
        label: "Passed the previous grade with no failed subject",
        detail: "Academic progress is monitored termly rather than at entry only.",
      },
      {
        id: "commitment",
        label: "Commits to school squad representation",
        detail: "Holders represent the school at inter-school and district fixtures.",
      },
    ],
    benefits: [
      "50% tuition waiver, renewable annually",
      "Full sports kit and footwear each session",
      "Travel and accommodation support for representative fixtures",
      "Documented catch-up arrangement with every subject teacher",
      "Priority access to the covered court and ground outside class hours",
    ],
    documents: [
      "Completed application form",
      "District or provincial association participation certificate",
      "Previous grade transcript",
      "Medical fitness note from a registered practitioner",
      "Two passport-size photographs in sports attire",
    ],
    process: [
      "Submit the form with the association certificate",
      "Attend the selection trial on Mangsir 14",
      "Panel assessment with the district association representative",
      "Written decision and catch-up plan issued together by Mangsir 25",
    ],
    renewal: `Renewed annually on continued representation, passing all subjects, and attendance of at least 70 percent counting authorised fixture absence as present.`,
    contact: "Tek Bahadur Rai, Head of Physical Education · t.rai@everestbutwal.edu.np · Ext. 270",
  },
  {
    id: "arts-grant",
    ref: "SCH/2083/ART/07",
    name: "Performing and Visual Arts Grant",
    nepaliName: "प्रदर्शन तथा दृश्य कला अनुदान",
    category: "Arts",
    coverage: 40,
    award: "40% tuition waiver with studio access and materials",
    amountNpr: 38900,
    seats: 6,
    deadlineAd: "2026-12-20",
    deadlineBs: "Poush 5, 2083",
    appliesTo: "Grade 9 to Grade 12",
    summary: `A portfolio- or audition-based award for students working seriously in music, dramatics, or visual art.`,
    description: `Selection is on the strength of a submitted portfolio or a live audition — not on academic ranking. Holders receive booked studio time in their own name, a materials allowance, and a commitment to lead at least one public performance or exhibition each session. Six places are shared between performing and visual arts.`,
    eligibility: [
      {
        id: "portfolio",
        label: "Portfolio of ten works or a live audition",
        detail: "Visual art: ten pieces. Music and dramatics: a ten-minute live audition.",
      },
      {
        id: "academic",
        label: "Passed the previous grade",
        detail: "No minimum GPA is applied to this scheme by design.",
      },
      {
        id: "contribution",
        label: "Commits to one public performance or exhibition per session",
        detail: "Counted as part of the award, not as an extra obligation.",
      },
    ],
    benefits: [
      "40% tuition waiver, renewable annually",
      "Materials allowance of Rs 9,000 per session",
      "Bookable studio time in the holder's own name",
      "Mentoring from the Arts and Culture Committee",
      "Guaranteed slot in the annual programme and gallery rotation",
    ],
    documents: [
      "Completed application form",
      "Portfolio of ten works, or an audition booking slip",
      "Previous grade transcript",
      "A one-page statement of intent written by the student",
      "Two passport-size photographs",
    ],
    process: [
      "Submit the form with the portfolio or book an audition slot",
      "Portfolio review or live audition in the week of Poush 8",
      "Short conversation with the Arts and Culture Committee",
      "Written decision issued by Poush 18",
    ],
    renewal: `Renewed annually on completing the public performance or exhibition commitment and passing all subjects.`,
    contact: "Rekha Subedi, Head of English & Arts Committee · r.subedi@everestbutwal.edu.np · Ext. 230",
  },
  {
    id: "single-parent-support",
    ref: "SCH/2083/NED/08",
    name: "Single-Parent and Martyr Family Support",
    nepaliName: "एकल अभिभावक तथा शहीद परिवार सहयोग",
    category: "Need-based",
    coverage: 85,
    award: "85% tuition waiver with examination fee cover",
    amountNpr: 122400,
    seats: 9,
    deadlineAd: "2027-01-10",
    deadlineBs: "Poush 26, 2083",
    appliesTo: "All levels · Grade 1 to Grade 12",
    summary: `For students being raised by a single parent or guardian, and for children of martyrs and conflict victims.`,
    description: `This scheme is intentionally documentation-light: a death or divorce certificate, or a martyr family certificate, plus an income declaration. There is no academic threshold and no interview for the student — the conversation is with the guardian only, and it is short. Nine places are available across all levels.`,
    eligibility: [
      {
        id: "status",
        label: "Raised by a single parent or guardian, or child of a martyr or conflict victim",
        detail: "Evidenced by a death certificate, divorce decree, or martyr family certificate.",
      },
      {
        id: "income",
        label: "Annual household income below Rs 500,000",
        detail: "Ward-office attested declaration required.",
      },
      {
        id: "passed",
        label: "Passed the previous grade",
        detail: "No minimum GPA is applied to this scheme.",
      },
    ],
    benefits: [
      "85% tuition waiver, renewable annually",
      "Full examination and board fee cover",
      "Free textbook set from library stock",
      "Counselling centre priority appointments",
      "Flexible fee scheduling through the accounts desk",
    ],
    documents: [
      "Completed application form",
      "Death certificate, divorce decree, or martyr family certificate",
      "Ward-office income declaration",
      "Previous grade transcript or transfer certificate",
      "Guardian's citizenship copy",
      "Two passport-size photographs",
    ],
    process: [
      "Submit the form with the status and income documents",
      "Short conversation with the guardian only — no student interview",
      "Written decision issued by Magh 8",
      "Fee schedule agreed at the accounts desk before the next invoice",
    ],
    renewal: `Renewed annually on continued status and income eligibility and on passing the grade. No re-interview is required.`,
    contact: "Nisha Baral, Admissions Officer · admissions@everestbutwal.edu.np · Ext. 110",
  },
  {
    id: "municipality-talent",
    ref: "SCH/2083/COM/09",
    name: "Butwal Municipality Local Talent Scholarship",
    nepaliName: "बुटवल उपमहानगरपालिका स्थानीय प्रतिभा छात्रवृत्ति",
    category: "Community",
    coverage: 45,
    award: "45% tuition waiver, part-funded by the municipality",
    amountNpr: 43700,
    seats: 14,
    deadlineAd: "2026-10-30",
    deadlineBs: "Kartik 13, 2083",
    appliesTo: "Grade 6 to Grade 12 · Butwal Sub-Metropolitan residents",
    summary: `A jointly funded award for students resident in Butwal Sub-Metropolitan City, with a light local-contribution expectation.`,
    description: `Half of this award is funded by Butwal Sub-Metropolitan City and half by the school. It is open to residents of any ward within the sub-metropolitan area and carries a modest expectation of local contribution — twenty hours a session with the Eco Club, the community reading programme, or a municipal campaign. Fourteen places are available.`,
    eligibility: [
      {
        id: "residency",
        label: "Resident of any ward in Butwal Sub-Metropolitan City",
        detail: "Ward recommendation letter required as proof of residence.",
      },
      {
        id: "academic",
        label: "Minimum GPA 2.80 in the last completed year",
        detail: "Or a demonstrated strength in a co-curricular field.",
      },
      {
        id: "income",
        label: "Annual household income below Rs 700,000",
        detail: "Ward-office attested declaration required.",
      },
      {
        id: "service",
        label: "Twenty hours of local contribution per session",
        detail: "Eco Club, community reading programme, or a municipal campaign. Logged by the faculty advisor.",
      },
    ],
    benefits: [
      "45% tuition waiver, renewable annually",
      "Municipal certificate of recognition each session",
      "Free library membership and priority carrel access",
      "Community leadership record on the school transcript",
    ],
    documents: [
      "Completed application form",
      "Ward recommendation letter confirming residence",
      "Ward-office income declaration",
      "Last completed academic transcript",
      "Two passport-size photographs",
    ],
    process: [
      "Obtain the ward recommendation letter",
      "Submit the form at the admissions desk before the deadline",
      "Joint review by the school committee and a municipal representative",
      "Written decision issued by Mangsir 2",
      "Register your contribution activity with the faculty advisor",
    ],
    renewal: `Renewed annually on completing the twenty logged contribution hours, maintaining GPA 2.60, and continued residence in the sub-metropolitan area.`,
    contact: "Kabita Shrestha, Coordinator (Secondary Level) · coord.secondary@everestbutwal.edu.np · Ext. 120",
  },
];

export const scholarshipCategories = Array.from(
  new Set(scholarships.map((s) => s.category)),
).sort();

export const totalScholarshipSeats = scholarships.reduce(
  (sum, s) => sum + s.seats,
  0,
);
