import { Download, Receipt } from "lucide-react";
import { toast } from "sonner";
import type { PaymentTransaction } from "#/types";
import { Button } from "#/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "#/components/ui/dialog";
import { StatusBadge } from "#/components/common/StatusBadge";
import { downloadTextFile, formatCurrency, formatDateTime } from "#/lib/format";
import { METHOD_LABEL } from "./payments-constants";

interface ReceiptDialogProps {
  payment: PaymentTransaction | null;
  onOpenChange: (open: boolean) => void;
  schoolName?: string;
}

function Line({ label, value, testId }: { label: string; value: React.ReactNode; testId?: string }) {
  return (
    <div className="flex items-start justify-between gap-4 py-1.5">
      <span className="text-xs text-muted-foreground">{label}</span>
      <span className="num max-w-[60%] truncate text-right text-xs font-medium text-foreground" data-testid={testId}>
        {value}
      </span>
    </div>
  );
}

export function ReceiptDialog({ payment, onOpenChange, schoolName = "Everest English Boarding Secondary School" }: ReceiptDialogProps) {
  const download = () => {
    if (!payment) return;
    const lines = [
      schoolName,
      "Payment receipt",
      "",
      `Receipt no      : ${payment.receiptNo}`,
      `Invoice no      : ${payment.invoiceNo}`,
      `Student         : ${payment.studentName}`,
      `Amount          : ${formatCurrency(payment.amount)}`,
      `Method          : ${METHOD_LABEL[payment.method]}`,
      `Reference       : ${payment.reference}`,
      `Status          : ${payment.status}`,
      `Paid at         : ${formatDateTime(payment.paidAt)}`,
      `Recorded by     : ${payment.recordedBy}`,
      "",
      "This is a demo receipt generated by the ScMS admin template.",
    ];
    downloadTextFile(`${payment.receiptNo}.txt`, lines.join("\n"), "text/plain");
    toast.success(`${payment.receiptNo} downloaded`);
  };

  return (
    <Dialog open={Boolean(payment)} onOpenChange={onOpenChange}>
      <DialogContent className="border-hairline bg-popover sm:max-w-md" data-testid="receipt-dialog">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 font-display">
            <Receipt className="h-4 w-4 text-primary" /> Receipt
          </DialogTitle>
          <DialogDescription>
            {payment ? `${payment.receiptNo} · ${payment.studentName}` : "No receipt selected."}
          </DialogDescription>
        </DialogHeader>

        {payment && (
          <div className="rounded-xl border border-hairline bg-surface-2 p-4" data-testid="receipt-dialog-body">
            <div className="flex items-start justify-between gap-3 border-b border-hairline pb-3">
              <div className="min-w-0">
                <p className="font-display text-sm font-semibold text-foreground">{schoolName}</p>
                <p className="text-[11px] text-muted-foreground">Fee payment receipt</p>
              </div>
              <StatusBadge value={payment.status} testId="receipt-dialog-status" />
            </div>

            <p className="num mt-3 font-display text-2xl font-semibold leading-none text-foreground" data-testid="receipt-dialog-amount">
              {formatCurrency(payment.amount)}
            </p>
            <p className="mt-1 text-[11px] text-muted-foreground">{formatDateTime(payment.paidAt)}</p>

            <div className="mt-3 divide-y divide-hairline border-t border-hairline pt-1">
              <Line label="Receipt no" value={payment.receiptNo} testId="receipt-dialog-no" />
              <Line label="Invoice" value={payment.invoiceNo} />
              <Line label="Student" value={payment.studentName} />
              <Line label="Method" value={METHOD_LABEL[payment.method]} />
              <Line label="Reference" value={payment.reference} />
              <Line label="Recorded by" value={payment.recordedBy} />
            </div>
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} data-testid="receipt-dialog-close">
            Close
          </Button>
          <Button className="gap-1.5" onClick={download} data-testid="receipt-dialog-download">
            <Download className="h-3.5 w-3.5" /> Download
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
