/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as OnboardRouteImport } from './routes/_onboard'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UserScholarshipsPageDetailRouteImport } from './routes/user/scholarships-page-detail'
import { Route as UserNoticesPageDetailRouteImport } from './routes/user/notices-page-detail'
import { Route as UserLoginModernRouteImport } from './routes/user/login-modern'
import { Route as UserHomePageRouteImport } from './routes/user/home-page'
import { Route as UserGalleryRouteImport } from './routes/user/gallery'
import { Route as UserFacultyPageDetailRouteImport } from './routes/user/faculty-page-detail'
import { Route as UserFacilitiesPageDetailRouteImport } from './routes/user/facilities-page-detail'
import { Route as UserFacilitiesAltRouteImport } from './routes/user/facilities-alt'
import { Route as UserFacilitiesRouteImport } from './routes/user/facilities'
import { Route as UserCoursesPageDetailRouteImport } from './routes/user/courses-page-detail'
import { Route as UserCoursesAltRouteImport } from './routes/user/courses-alt'
import { Route as UserCoursesRouteImport } from './routes/user/courses'
import { Route as UserContactPageDetailRouteImport } from './routes/user/contact-page-detail'
import { Route as UserContactAltRouteImport } from './routes/user/contact-alt'
import { Route as UserContactRouteImport } from './routes/user/contact'
import { Route as UserCalendarRouteImport } from './routes/user/calendar'
import { Route as UserAboutPageDetailRouteImport } from './routes/user/about-page-detail'
import { Route as UserAboutAltRouteImport } from './routes/user/about-alt'
import { Route as UserAboutRouteImport } from './routes/user/about'
import { Route as AdminWebsiteRouteImport } from './routes/admin/website'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransportationRouteImport } from './routes/admin/transportation'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminClassesRouteImport } from './routes/admin/classes'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminAdmissionsRouteImport } from './routes/admin/admissions'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicFacilitiesRouteImport } from './routes/_public/facilities'
import { Route as PublicCoursesRouteImport } from './routes/_public/courses'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCalendarRouteImport } from './routes/_public/calendar'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as OnboardSignupRouteImport } from './routes/_onboard/signup'
import { Route as OnboardLoginModernRouteImport } from './routes/_onboard/login-modern'
import { Route as ApiWebsitePagesRouteImport } from './routes/api/website/pages'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students.$id'
import { Route as AdminStaffIdRouteImport } from './routes/admin/staff.$id'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin/payments.$id'
import { Route as AdminNoticesNewRouteImport } from './routes/admin/notices.new'
import { Route as AdminNoticesIdRouteImport } from './routes/admin/notices.$id'
import { Route as AdminGalleryIdRouteImport } from './routes/admin/gallery.$id'
import { Route as AdminEventsIdRouteImport } from './routes/admin/events.$id'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses.$id'
import { Route as AdminClassesIdRouteImport } from './routes/admin/classes.$id'
import { Route as AdminAdmissionsIdRouteImport } from './routes/admin/admissions.$id'
import { Route as OnboardActivateTokenRouteImport } from './routes/_onboard/activate.$token'
import { Route as ApiWebsitePagesKeyRouteImport } from './routes/api/website/pages/$key'
import { Route as ApiWebsitePageKeyRouteImport } from './routes/api/website/page/$key'
import { Route as AdminNoticesIdEditRouteImport } from './routes/admin/notices.$id.edit'
import { Route as ApiWebsitePagesKeyUnpublishRouteImport } from './routes/api/website/pages/$key/unpublish'
import { Route as ApiWebsitePagesKeyPublishRouteImport } from './routes/api/website/pages/$key/publish'
import { Route as ApiWebsitePagesKeyBlocksRouteImport } from './routes/api/website/pages/$key/blocks'
import { Route as ApiWebsitePagesKeySectionsSectionTypeRouteImport } from './routes/api/website/pages/$key/sections/$sectionType'
import { Route as ApiWebsitePagesKeyBlocksBlockIdRouteImport } from './routes/api/website/pages/$key/blocks/$blockId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/_onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const UserScholarshipsPageDetailRoute =
  UserScholarshipsPageDetailRouteImport.update({
    id: '/scholarships-page-detail',
    path: '/scholarships-page-detail',
    getParentRoute: () => UserRoute,
  } as any)
const UserNoticesPageDetailRoute = UserNoticesPageDetailRouteImport.update({
  id: '/notices-page-detail',
  path: '/notices-page-detail',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginModernRoute = UserLoginModernRouteImport.update({
  id: '/login-modern',
  path: '/login-modern',
  getParentRoute: () => UserRoute,
} as any)
const UserHomePageRoute = UserHomePageRouteImport.update({
  id: '/home-page',
  path: '/home-page',
  getParentRoute: () => UserRoute,
} as any)
const UserGalleryRoute = UserGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => UserRoute,
} as any)
const UserFacultyPageDetailRoute = UserFacultyPageDetailRouteImport.update({
  id: '/faculty-page-detail',
  path: '/faculty-page-detail',
  getParentRoute: () => UserRoute,
} as any)
const UserFacilitiesPageDetailRoute =
  UserFacilitiesPageDetailRouteImport.update({
    id: '/facilities-page-detail',
    path: '/facilities-page-detail',
    getParentRoute: () => UserRoute,
  } as any)
const UserFacilitiesAltRoute = UserFacilitiesAltRouteImport.update({
  id: '/facilities-alt',
  path: '/facilities-alt',
  getParentRoute: () => UserRoute,
} as any)
const UserFacilitiesRoute = UserFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => UserRoute,
} as any)
const UserCoursesPageDetailRoute = UserCoursesPageDetailRouteImport.update({
  id: '/courses-page-detail',
  path: '/courses-page-detail',
  getParentRoute: () => UserRoute,
} as any)
const UserCoursesAltRoute = UserCoursesAltRouteImport.update({
  id: '/courses-alt',
  path: '/courses-alt',
  getParentRoute: () => UserRoute,
} as any)
const UserCoursesRoute = UserCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => UserRoute,
} as any)
const UserContactPageDetailRoute = UserContactPageDetailRouteImport.update({
  id: '/contact-page-detail',
  path: '/contact-page-detail',
  getParentRoute: () => UserRoute,
} as any)
const UserContactAltRoute = UserContactAltRouteImport.update({
  id: '/contact-alt',
  path: '/contact-alt',
  getParentRoute: () => UserRoute,
} as any)
const UserContactRoute = UserContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UserRoute,
} as any)
const UserCalendarRoute = UserCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => UserRoute,
} as any)
const UserAboutPageDetailRoute = UserAboutPageDetailRouteImport.update({
  id: '/about-page-detail',
  path: '/about-page-detail',
  getParentRoute: () => UserRoute,
} as any)
const UserAboutAltRoute = UserAboutAltRouteImport.update({
  id: '/about-alt',
  path: '/about-alt',
  getParentRoute: () => UserRoute,
} as any)
const UserAboutRoute = UserAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => UserRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransportationRoute = AdminTransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFacilitiesRoute = PublicFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCalendarRoute = PublicCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const OnboardSignupRoute = OnboardSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => OnboardRoute,
} as any)
const OnboardLoginModernRoute = OnboardLoginModernRouteImport.update({
  id: '/login-modern',
  path: '/login-modern',
  getParentRoute: () => OnboardRoute,
} as any)
const ApiWebsitePagesRoute = ApiWebsitePagesRouteImport.update({
  id: '/api/website/pages',
  path: '/api/website/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStudentsRoute,
} as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStaffRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminNoticesNewRoute = AdminNoticesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNoticesRoute,
} as any)
const AdminNoticesIdRoute = AdminNoticesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNoticesRoute,
} as any)
const AdminGalleryIdRoute = AdminGalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminGalleryRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminClassesIdRoute = AdminClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClassesRoute,
} as any)
const AdminAdmissionsIdRoute = AdminAdmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdmissionsRoute,
} as any)
const OnboardActivateTokenRoute = OnboardActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => OnboardRoute,
} as any)
const ApiWebsitePagesKeyRoute = ApiWebsitePagesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiWebsitePagesRoute,
} as any)
const ApiWebsitePageKeyRoute = ApiWebsitePageKeyRouteImport.update({
  id: '/api/website/page/$key',
  path: '/api/website/page/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticesIdEditRoute = AdminNoticesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminNoticesIdRoute,
} as any)
const ApiWebsitePagesKeyUnpublishRoute =
  ApiWebsitePagesKeyUnpublishRouteImport.update({
    id: '/unpublish',
    path: '/unpublish',
    getParentRoute: () => ApiWebsitePagesKeyRoute,
  } as any)
const ApiWebsitePagesKeyPublishRoute =
  ApiWebsitePagesKeyPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiWebsitePagesKeyRoute,
  } as any)
const ApiWebsitePagesKeyBlocksRoute =
  ApiWebsitePagesKeyBlocksRouteImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => ApiWebsitePagesKeyRoute,
  } as any)
const ApiWebsitePagesKeySectionsSectionTypeRoute =
  ApiWebsitePagesKeySectionsSectionTypeRouteImport.update({
    id: '/sections/$sectionType',
    path: '/sections/$sectionType',
    getParentRoute: () => ApiWebsitePagesKeyRoute,
  } as any)
const ApiWebsitePagesKeyBlocksBlockIdRoute =
  ApiWebsitePagesKeyBlocksBlockIdRouteImport.update({
    id: '/$blockId',
    path: '/$blockId',
    getParentRoute: () => ApiWebsitePagesKeyBlocksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/login-modern': typeof OnboardLoginModernRoute
  '/signup': typeof OnboardSignupRoute
  '/about': typeof PublicAboutRoute
  '/calendar': typeof PublicCalendarRoute
  '/contact': typeof PublicContactRoute
  '/courses': typeof PublicCoursesRoute
  '/facilities': typeof PublicFacilitiesRoute
  '/gallery': typeof PublicGalleryRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRouteWithChildren
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteWithChildren
  '/admin/notices': typeof AdminNoticesRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/transportation': typeof AdminTransportationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/user/about': typeof UserAboutRoute
  '/user/about-alt': typeof UserAboutAltRoute
  '/user/about-page-detail': typeof UserAboutPageDetailRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/contact': typeof UserContactRoute
  '/user/contact-alt': typeof UserContactAltRoute
  '/user/contact-page-detail': typeof UserContactPageDetailRoute
  '/user/courses': typeof UserCoursesRoute
  '/user/courses-alt': typeof UserCoursesAltRoute
  '/user/courses-page-detail': typeof UserCoursesPageDetailRoute
  '/user/facilities': typeof UserFacilitiesRoute
  '/user/facilities-alt': typeof UserFacilitiesAltRoute
  '/user/facilities-page-detail': typeof UserFacilitiesPageDetailRoute
  '/user/faculty-page-detail': typeof UserFacultyPageDetailRoute
  '/user/gallery': typeof UserGalleryRoute
  '/user/home-page': typeof UserHomePageRoute
  '/user/login-modern': typeof UserLoginModernRoute
  '/user/notices-page-detail': typeof UserNoticesPageDetailRoute
  '/user/scholarships-page-detail': typeof UserScholarshipsPageDetailRoute
  '/admin/': typeof AdminIndexRoute
  '/activate/$token': typeof OnboardActivateTokenRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/website/pages': typeof ApiWebsitePagesRouteWithChildren
  '/admin/notices/$id/edit': typeof AdminNoticesIdEditRoute
  '/api/website/page/$key': typeof ApiWebsitePageKeyRoute
  '/api/website/pages/$key': typeof ApiWebsitePagesKeyRouteWithChildren
  '/api/website/pages/$key/blocks': typeof ApiWebsitePagesKeyBlocksRouteWithChildren
  '/api/website/pages/$key/publish': typeof ApiWebsitePagesKeyPublishRoute
  '/api/website/pages/$key/unpublish': typeof ApiWebsitePagesKeyUnpublishRoute
  '/api/website/pages/$key/blocks/$blockId': typeof ApiWebsitePagesKeyBlocksBlockIdRoute
  '/api/website/pages/$key/sections/$sectionType': typeof ApiWebsitePagesKeySectionsSectionTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/login-modern': typeof OnboardLoginModernRoute
  '/signup': typeof OnboardSignupRoute
  '/about': typeof PublicAboutRoute
  '/calendar': typeof PublicCalendarRoute
  '/contact': typeof PublicContactRoute
  '/courses': typeof PublicCoursesRoute
  '/facilities': typeof PublicFacilitiesRoute
  '/gallery': typeof PublicGalleryRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRouteWithChildren
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteWithChildren
  '/admin/notices': typeof AdminNoticesRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/transportation': typeof AdminTransportationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/user/about': typeof UserAboutRoute
  '/user/about-alt': typeof UserAboutAltRoute
  '/user/about-page-detail': typeof UserAboutPageDetailRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/contact': typeof UserContactRoute
  '/user/contact-alt': typeof UserContactAltRoute
  '/user/contact-page-detail': typeof UserContactPageDetailRoute
  '/user/courses': typeof UserCoursesRoute
  '/user/courses-alt': typeof UserCoursesAltRoute
  '/user/courses-page-detail': typeof UserCoursesPageDetailRoute
  '/user/facilities': typeof UserFacilitiesRoute
  '/user/facilities-alt': typeof UserFacilitiesAltRoute
  '/user/facilities-page-detail': typeof UserFacilitiesPageDetailRoute
  '/user/faculty-page-detail': typeof UserFacultyPageDetailRoute
  '/user/gallery': typeof UserGalleryRoute
  '/user/home-page': typeof UserHomePageRoute
  '/user/login-modern': typeof UserLoginModernRoute
  '/user/notices-page-detail': typeof UserNoticesPageDetailRoute
  '/user/scholarships-page-detail': typeof UserScholarshipsPageDetailRoute
  '/admin': typeof AdminIndexRoute
  '/activate/$token': typeof OnboardActivateTokenRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/website/pages': typeof ApiWebsitePagesRouteWithChildren
  '/admin/notices/$id/edit': typeof AdminNoticesIdEditRoute
  '/api/website/page/$key': typeof ApiWebsitePageKeyRoute
  '/api/website/pages/$key': typeof ApiWebsitePagesKeyRouteWithChildren
  '/api/website/pages/$key/blocks': typeof ApiWebsitePagesKeyBlocksRouteWithChildren
  '/api/website/pages/$key/publish': typeof ApiWebsitePagesKeyPublishRoute
  '/api/website/pages/$key/unpublish': typeof ApiWebsitePagesKeyUnpublishRoute
  '/api/website/pages/$key/blocks/$blockId': typeof ApiWebsitePagesKeyBlocksBlockIdRoute
  '/api/website/pages/$key/sections/$sectionType': typeof ApiWebsitePagesKeySectionsSectionTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_onboard': typeof OnboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/user': typeof UserRouteWithChildren
  '/_onboard/login-modern': typeof OnboardLoginModernRoute
  '/_onboard/signup': typeof OnboardSignupRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/calendar': typeof PublicCalendarRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/courses': typeof PublicCoursesRoute
  '/_public/facilities': typeof PublicFacilitiesRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRouteWithChildren
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRouteWithChildren
  '/admin/notices': typeof AdminNoticesRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/admin/transportation': typeof AdminTransportationRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/user/about': typeof UserAboutRoute
  '/user/about-alt': typeof UserAboutAltRoute
  '/user/about-page-detail': typeof UserAboutPageDetailRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/contact': typeof UserContactRoute
  '/user/contact-alt': typeof UserContactAltRoute
  '/user/contact-page-detail': typeof UserContactPageDetailRoute
  '/user/courses': typeof UserCoursesRoute
  '/user/courses-alt': typeof UserCoursesAltRoute
  '/user/courses-page-detail': typeof UserCoursesPageDetailRoute
  '/user/facilities': typeof UserFacilitiesRoute
  '/user/facilities-alt': typeof UserFacilitiesAltRoute
  '/user/facilities-page-detail': typeof UserFacilitiesPageDetailRoute
  '/user/faculty-page-detail': typeof UserFacultyPageDetailRoute
  '/user/gallery': typeof UserGalleryRoute
  '/user/home-page': typeof UserHomePageRoute
  '/user/login-modern': typeof UserLoginModernRoute
  '/user/notices-page-detail': typeof UserNoticesPageDetailRoute
  '/user/scholarships-page-detail': typeof UserScholarshipsPageDetailRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_onboard/activate/$token': typeof OnboardActivateTokenRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/gallery/$id': typeof AdminGalleryIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRouteWithChildren
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/website/pages': typeof ApiWebsitePagesRouteWithChildren
  '/admin/notices/$id/edit': typeof AdminNoticesIdEditRoute
  '/api/website/page/$key': typeof ApiWebsitePageKeyRoute
  '/api/website/pages/$key': typeof ApiWebsitePagesKeyRouteWithChildren
  '/api/website/pages/$key/blocks': typeof ApiWebsitePagesKeyBlocksRouteWithChildren
  '/api/website/pages/$key/publish': typeof ApiWebsitePagesKeyPublishRoute
  '/api/website/pages/$key/unpublish': typeof ApiWebsitePagesKeyUnpublishRoute
  '/api/website/pages/$key/blocks/$blockId': typeof ApiWebsitePagesKeyBlocksBlockIdRoute
  '/api/website/pages/$key/sections/$sectionType': typeof ApiWebsitePagesKeySectionsSectionTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/login-modern'
    | '/signup'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/courses'
    | '/facilities'
    | '/gallery'
    | '/admin/$'
    | '/admin/activity'
    | '/admin/admissions'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/notices'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transportation'
    | '/admin/users'
    | '/admin/website'
    | '/user/about'
    | '/user/about-alt'
    | '/user/about-page-detail'
    | '/user/calendar'
    | '/user/contact'
    | '/user/contact-alt'
    | '/user/contact-page-detail'
    | '/user/courses'
    | '/user/courses-alt'
    | '/user/courses-page-detail'
    | '/user/facilities'
    | '/user/facilities-alt'
    | '/user/facilities-page-detail'
    | '/user/faculty-page-detail'
    | '/user/gallery'
    | '/user/home-page'
    | '/user/login-modern'
    | '/user/notices-page-detail'
    | '/user/scholarships-page-detail'
    | '/admin/'
    | '/activate/$token'
    | '/admin/admissions/$id'
    | '/admin/classes/$id'
    | '/admin/courses/$id'
    | '/admin/events/$id'
    | '/admin/gallery/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/payments/$id'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/api/auth/$'
    | '/api/website/pages'
    | '/admin/notices/$id/edit'
    | '/api/website/page/$key'
    | '/api/website/pages/$key'
    | '/api/website/pages/$key/blocks'
    | '/api/website/pages/$key/publish'
    | '/api/website/pages/$key/unpublish'
    | '/api/website/pages/$key/blocks/$blockId'
    | '/api/website/pages/$key/sections/$sectionType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/user'
    | '/login-modern'
    | '/signup'
    | '/about'
    | '/calendar'
    | '/contact'
    | '/courses'
    | '/facilities'
    | '/gallery'
    | '/admin/$'
    | '/admin/activity'
    | '/admin/admissions'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/notices'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transportation'
    | '/admin/users'
    | '/admin/website'
    | '/user/about'
    | '/user/about-alt'
    | '/user/about-page-detail'
    | '/user/calendar'
    | '/user/contact'
    | '/user/contact-alt'
    | '/user/contact-page-detail'
    | '/user/courses'
    | '/user/courses-alt'
    | '/user/courses-page-detail'
    | '/user/facilities'
    | '/user/facilities-alt'
    | '/user/facilities-page-detail'
    | '/user/faculty-page-detail'
    | '/user/gallery'
    | '/user/home-page'
    | '/user/login-modern'
    | '/user/notices-page-detail'
    | '/user/scholarships-page-detail'
    | '/admin'
    | '/activate/$token'
    | '/admin/admissions/$id'
    | '/admin/classes/$id'
    | '/admin/courses/$id'
    | '/admin/events/$id'
    | '/admin/gallery/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/payments/$id'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/api/auth/$'
    | '/api/website/pages'
    | '/admin/notices/$id/edit'
    | '/api/website/page/$key'
    | '/api/website/pages/$key'
    | '/api/website/pages/$key/blocks'
    | '/api/website/pages/$key/publish'
    | '/api/website/pages/$key/unpublish'
    | '/api/website/pages/$key/blocks/$blockId'
    | '/api/website/pages/$key/sections/$sectionType'
  id:
    | '__root__'
    | '/_onboard'
    | '/_public'
    | '/admin'
    | '/login'
    | '/user'
    | '/_onboard/login-modern'
    | '/_onboard/signup'
    | '/_public/about'
    | '/_public/calendar'
    | '/_public/contact'
    | '/_public/courses'
    | '/_public/facilities'
    | '/_public/gallery'
    | '/admin/$'
    | '/admin/activity'
    | '/admin/admissions'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/notices'
    | '/admin/overview'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transportation'
    | '/admin/users'
    | '/admin/website'
    | '/user/about'
    | '/user/about-alt'
    | '/user/about-page-detail'
    | '/user/calendar'
    | '/user/contact'
    | '/user/contact-alt'
    | '/user/contact-page-detail'
    | '/user/courses'
    | '/user/courses-alt'
    | '/user/courses-page-detail'
    | '/user/facilities'
    | '/user/facilities-alt'
    | '/user/facilities-page-detail'
    | '/user/faculty-page-detail'
    | '/user/gallery'
    | '/user/home-page'
    | '/user/login-modern'
    | '/user/notices-page-detail'
    | '/user/scholarships-page-detail'
    | '/_public/'
    | '/admin/'
    | '/_onboard/activate/$token'
    | '/admin/admissions/$id'
    | '/admin/classes/$id'
    | '/admin/courses/$id'
    | '/admin/events/$id'
    | '/admin/gallery/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/payments/$id'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/api/auth/$'
    | '/api/website/pages'
    | '/admin/notices/$id/edit'
    | '/api/website/page/$key'
    | '/api/website/pages/$key'
    | '/api/website/pages/$key/blocks'
    | '/api/website/pages/$key/publish'
    | '/api/website/pages/$key/unpublish'
    | '/api/website/pages/$key/blocks/$blockId'
    | '/api/website/pages/$key/sections/$sectionType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardRoute: typeof OnboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  UserRoute: typeof UserRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebsitePagesRoute: typeof ApiWebsitePagesRouteWithChildren
  ApiWebsitePageKeyRoute: typeof ApiWebsitePageKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboard': {
      id: '/_onboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/user/scholarships-page-detail': {
      id: '/user/scholarships-page-detail'
      path: '/scholarships-page-detail'
      fullPath: '/user/scholarships-page-detail'
      preLoaderRoute: typeof UserScholarshipsPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/notices-page-detail': {
      id: '/user/notices-page-detail'
      path: '/notices-page-detail'
      fullPath: '/user/notices-page-detail'
      preLoaderRoute: typeof UserNoticesPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/login-modern': {
      id: '/user/login-modern'
      path: '/login-modern'
      fullPath: '/user/login-modern'
      preLoaderRoute: typeof UserLoginModernRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/home-page': {
      id: '/user/home-page'
      path: '/home-page'
      fullPath: '/user/home-page'
      preLoaderRoute: typeof UserHomePageRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/gallery': {
      id: '/user/gallery'
      path: '/gallery'
      fullPath: '/user/gallery'
      preLoaderRoute: typeof UserGalleryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/faculty-page-detail': {
      id: '/user/faculty-page-detail'
      path: '/faculty-page-detail'
      fullPath: '/user/faculty-page-detail'
      preLoaderRoute: typeof UserFacultyPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/facilities-page-detail': {
      id: '/user/facilities-page-detail'
      path: '/facilities-page-detail'
      fullPath: '/user/facilities-page-detail'
      preLoaderRoute: typeof UserFacilitiesPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/facilities-alt': {
      id: '/user/facilities-alt'
      path: '/facilities-alt'
      fullPath: '/user/facilities-alt'
      preLoaderRoute: typeof UserFacilitiesAltRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/facilities': {
      id: '/user/facilities'
      path: '/facilities'
      fullPath: '/user/facilities'
      preLoaderRoute: typeof UserFacilitiesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/courses-page-detail': {
      id: '/user/courses-page-detail'
      path: '/courses-page-detail'
      fullPath: '/user/courses-page-detail'
      preLoaderRoute: typeof UserCoursesPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/courses-alt': {
      id: '/user/courses-alt'
      path: '/courses-alt'
      fullPath: '/user/courses-alt'
      preLoaderRoute: typeof UserCoursesAltRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/courses': {
      id: '/user/courses'
      path: '/courses'
      fullPath: '/user/courses'
      preLoaderRoute: typeof UserCoursesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/contact-page-detail': {
      id: '/user/contact-page-detail'
      path: '/contact-page-detail'
      fullPath: '/user/contact-page-detail'
      preLoaderRoute: typeof UserContactPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/contact-alt': {
      id: '/user/contact-alt'
      path: '/contact-alt'
      fullPath: '/user/contact-alt'
      preLoaderRoute: typeof UserContactAltRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/contact': {
      id: '/user/contact'
      path: '/contact'
      fullPath: '/user/contact'
      preLoaderRoute: typeof UserContactRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/calendar': {
      id: '/user/calendar'
      path: '/calendar'
      fullPath: '/user/calendar'
      preLoaderRoute: typeof UserCalendarRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/about-page-detail': {
      id: '/user/about-page-detail'
      path: '/about-page-detail'
      fullPath: '/user/about-page-detail'
      preLoaderRoute: typeof UserAboutPageDetailRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/about-alt': {
      id: '/user/about-alt'
      path: '/about-alt'
      fullPath: '/user/about-alt'
      preLoaderRoute: typeof UserAboutAltRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/about': {
      id: '/user/about'
      path: '/about'
      fullPath: '/user/about'
      preLoaderRoute: typeof UserAboutRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transportation': {
      id: '/admin/transportation'
      path: '/transportation'
      fullPath: '/admin/transportation'
      preLoaderRoute: typeof AdminTransportationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/facilities': {
      id: '/_public/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof PublicFacilitiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses': {
      id: '/_public/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/calendar': {
      id: '/_public/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PublicCalendarRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_onboard/signup': {
      id: '/_onboard/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof OnboardSignupRouteImport
      parentRoute: typeof OnboardRoute
    }
    '/_onboard/login-modern': {
      id: '/_onboard/login-modern'
      path: '/login-modern'
      fullPath: '/login-modern'
      preLoaderRoute: typeof OnboardLoginModernRouteImport
      parentRoute: typeof OnboardRoute
    }
    '/api/website/pages': {
      id: '/api/website/pages'
      path: '/api/website/pages'
      fullPath: '/api/website/pages'
      preLoaderRoute: typeof ApiWebsitePagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/notices/new': {
      id: '/admin/notices/new'
      path: '/new'
      fullPath: '/admin/notices/new'
      preLoaderRoute: typeof AdminNoticesNewRouteImport
      parentRoute: typeof AdminNoticesRoute
    }
    '/admin/notices/$id': {
      id: '/admin/notices/$id'
      path: '/$id'
      fullPath: '/admin/notices/$id'
      preLoaderRoute: typeof AdminNoticesIdRouteImport
      parentRoute: typeof AdminNoticesRoute
    }
    '/admin/gallery/$id': {
      id: '/admin/gallery/$id'
      path: '/$id'
      fullPath: '/admin/gallery/$id'
      preLoaderRoute: typeof AdminGalleryIdRouteImport
      parentRoute: typeof AdminGalleryRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/classes/$id': {
      id: '/admin/classes/$id'
      path: '/$id'
      fullPath: '/admin/classes/$id'
      preLoaderRoute: typeof AdminClassesIdRouteImport
      parentRoute: typeof AdminClassesRoute
    }
    '/admin/admissions/$id': {
      id: '/admin/admissions/$id'
      path: '/$id'
      fullPath: '/admin/admissions/$id'
      preLoaderRoute: typeof AdminAdmissionsIdRouteImport
      parentRoute: typeof AdminAdmissionsRoute
    }
    '/_onboard/activate/$token': {
      id: '/_onboard/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof OnboardActivateTokenRouteImport
      parentRoute: typeof OnboardRoute
    }
    '/api/website/pages/$key': {
      id: '/api/website/pages/$key'
      path: '/$key'
      fullPath: '/api/website/pages/$key'
      preLoaderRoute: typeof ApiWebsitePagesKeyRouteImport
      parentRoute: typeof ApiWebsitePagesRoute
    }
    '/api/website/page/$key': {
      id: '/api/website/page/$key'
      path: '/api/website/page/$key'
      fullPath: '/api/website/page/$key'
      preLoaderRoute: typeof ApiWebsitePageKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notices/$id/edit': {
      id: '/admin/notices/$id/edit'
      path: '/edit'
      fullPath: '/admin/notices/$id/edit'
      preLoaderRoute: typeof AdminNoticesIdEditRouteImport
      parentRoute: typeof AdminNoticesIdRoute
    }
    '/api/website/pages/$key/unpublish': {
      id: '/api/website/pages/$key/unpublish'
      path: '/unpublish'
      fullPath: '/api/website/pages/$key/unpublish'
      preLoaderRoute: typeof ApiWebsitePagesKeyUnpublishRouteImport
      parentRoute: typeof ApiWebsitePagesKeyRoute
    }
    '/api/website/pages/$key/publish': {
      id: '/api/website/pages/$key/publish'
      path: '/publish'
      fullPath: '/api/website/pages/$key/publish'
      preLoaderRoute: typeof ApiWebsitePagesKeyPublishRouteImport
      parentRoute: typeof ApiWebsitePagesKeyRoute
    }
    '/api/website/pages/$key/blocks': {
      id: '/api/website/pages/$key/blocks'
      path: '/blocks'
      fullPath: '/api/website/pages/$key/blocks'
      preLoaderRoute: typeof ApiWebsitePagesKeyBlocksRouteImport
      parentRoute: typeof ApiWebsitePagesKeyRoute
    }
    '/api/website/pages/$key/sections/$sectionType': {
      id: '/api/website/pages/$key/sections/$sectionType'
      path: '/sections/$sectionType'
      fullPath: '/api/website/pages/$key/sections/$sectionType'
      preLoaderRoute: typeof ApiWebsitePagesKeySectionsSectionTypeRouteImport
      parentRoute: typeof ApiWebsitePagesKeyRoute
    }
    '/api/website/pages/$key/blocks/$blockId': {
      id: '/api/website/pages/$key/blocks/$blockId'
      path: '/$blockId'
      fullPath: '/api/website/pages/$key/blocks/$blockId'
      preLoaderRoute: typeof ApiWebsitePagesKeyBlocksBlockIdRouteImport
      parentRoute: typeof ApiWebsitePagesKeyBlocksRoute
    }
  }
}

interface OnboardRouteChildren {
  OnboardLoginModernRoute: typeof OnboardLoginModernRoute
  OnboardSignupRoute: typeof OnboardSignupRoute
  OnboardActivateTokenRoute: typeof OnboardActivateTokenRoute
}

const OnboardRouteChildren: OnboardRouteChildren = {
  OnboardLoginModernRoute: OnboardLoginModernRoute,
  OnboardSignupRoute: OnboardSignupRoute,
  OnboardActivateTokenRoute: OnboardActivateTokenRoute,
}

const OnboardRouteWithChildren =
  OnboardRoute._addFileChildren(OnboardRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCalendarRoute: typeof PublicCalendarRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCoursesRoute: typeof PublicCoursesRoute
  PublicFacilitiesRoute: typeof PublicFacilitiesRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCalendarRoute: PublicCalendarRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCoursesRoute: PublicCoursesRoute,
  PublicFacilitiesRoute: PublicFacilitiesRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminAdmissionsRouteChildren {
  AdminAdmissionsIdRoute: typeof AdminAdmissionsIdRoute
}

const AdminAdmissionsRouteChildren: AdminAdmissionsRouteChildren = {
  AdminAdmissionsIdRoute: AdminAdmissionsIdRoute,
}

const AdminAdmissionsRouteWithChildren = AdminAdmissionsRoute._addFileChildren(
  AdminAdmissionsRouteChildren,
)

interface AdminClassesRouteChildren {
  AdminClassesIdRoute: typeof AdminClassesIdRoute
}

const AdminClassesRouteChildren: AdminClassesRouteChildren = {
  AdminClassesIdRoute: AdminClassesIdRoute,
}

const AdminClassesRouteWithChildren = AdminClassesRoute._addFileChildren(
  AdminClassesRouteChildren,
)

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminEventsRouteChildren {
  AdminEventsIdRoute: typeof AdminEventsIdRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsIdRoute: AdminEventsIdRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminGalleryRouteChildren {
  AdminGalleryIdRoute: typeof AdminGalleryIdRoute
}

const AdminGalleryRouteChildren: AdminGalleryRouteChildren = {
  AdminGalleryIdRoute: AdminGalleryIdRoute,
}

const AdminGalleryRouteWithChildren = AdminGalleryRoute._addFileChildren(
  AdminGalleryRouteChildren,
)

interface AdminNoticesIdRouteChildren {
  AdminNoticesIdEditRoute: typeof AdminNoticesIdEditRoute
}

const AdminNoticesIdRouteChildren: AdminNoticesIdRouteChildren = {
  AdminNoticesIdEditRoute: AdminNoticesIdEditRoute,
}

const AdminNoticesIdRouteWithChildren = AdminNoticesIdRoute._addFileChildren(
  AdminNoticesIdRouteChildren,
)

interface AdminNoticesRouteChildren {
  AdminNoticesIdRoute: typeof AdminNoticesIdRouteWithChildren
  AdminNoticesNewRoute: typeof AdminNoticesNewRoute
}

const AdminNoticesRouteChildren: AdminNoticesRouteChildren = {
  AdminNoticesIdRoute: AdminNoticesIdRouteWithChildren,
  AdminNoticesNewRoute: AdminNoticesNewRoute,
}

const AdminNoticesRouteWithChildren = AdminNoticesRoute._addFileChildren(
  AdminNoticesRouteChildren,
)

interface AdminPaymentsRouteChildren {
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminStaffRouteChildren {
  AdminStaffIdRoute: typeof AdminStaffIdRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffIdRoute: AdminStaffIdRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface AdminStudentsRouteChildren {
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsIdRoute: AdminStudentsIdRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRouteWithChildren
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminClassesRoute: typeof AdminClassesRouteWithChildren
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminGalleryRoute: typeof AdminGalleryRouteWithChildren
  AdminNoticesRoute: typeof AdminNoticesRouteWithChildren
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminTransportationRoute: typeof AdminTransportationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAdmissionsRoute: AdminAdmissionsRouteWithChildren,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminClassesRoute: AdminClassesRouteWithChildren,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminGalleryRoute: AdminGalleryRouteWithChildren,
  AdminNoticesRoute: AdminNoticesRouteWithChildren,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRouteWithChildren,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminTransportationRoute: AdminTransportationRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserAboutRoute: typeof UserAboutRoute
  UserAboutAltRoute: typeof UserAboutAltRoute
  UserAboutPageDetailRoute: typeof UserAboutPageDetailRoute
  UserCalendarRoute: typeof UserCalendarRoute
  UserContactRoute: typeof UserContactRoute
  UserContactAltRoute: typeof UserContactAltRoute
  UserContactPageDetailRoute: typeof UserContactPageDetailRoute
  UserCoursesRoute: typeof UserCoursesRoute
  UserCoursesAltRoute: typeof UserCoursesAltRoute
  UserCoursesPageDetailRoute: typeof UserCoursesPageDetailRoute
  UserFacilitiesRoute: typeof UserFacilitiesRoute
  UserFacilitiesAltRoute: typeof UserFacilitiesAltRoute
  UserFacilitiesPageDetailRoute: typeof UserFacilitiesPageDetailRoute
  UserFacultyPageDetailRoute: typeof UserFacultyPageDetailRoute
  UserGalleryRoute: typeof UserGalleryRoute
  UserHomePageRoute: typeof UserHomePageRoute
  UserLoginModernRoute: typeof UserLoginModernRoute
  UserNoticesPageDetailRoute: typeof UserNoticesPageDetailRoute
  UserScholarshipsPageDetailRoute: typeof UserScholarshipsPageDetailRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAboutRoute: UserAboutRoute,
  UserAboutAltRoute: UserAboutAltRoute,
  UserAboutPageDetailRoute: UserAboutPageDetailRoute,
  UserCalendarRoute: UserCalendarRoute,
  UserContactRoute: UserContactRoute,
  UserContactAltRoute: UserContactAltRoute,
  UserContactPageDetailRoute: UserContactPageDetailRoute,
  UserCoursesRoute: UserCoursesRoute,
  UserCoursesAltRoute: UserCoursesAltRoute,
  UserCoursesPageDetailRoute: UserCoursesPageDetailRoute,
  UserFacilitiesRoute: UserFacilitiesRoute,
  UserFacilitiesAltRoute: UserFacilitiesAltRoute,
  UserFacilitiesPageDetailRoute: UserFacilitiesPageDetailRoute,
  UserFacultyPageDetailRoute: UserFacultyPageDetailRoute,
  UserGalleryRoute: UserGalleryRoute,
  UserHomePageRoute: UserHomePageRoute,
  UserLoginModernRoute: UserLoginModernRoute,
  UserNoticesPageDetailRoute: UserNoticesPageDetailRoute,
  UserScholarshipsPageDetailRoute: UserScholarshipsPageDetailRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface ApiWebsitePagesKeyBlocksRouteChildren {
  ApiWebsitePagesKeyBlocksBlockIdRoute: typeof ApiWebsitePagesKeyBlocksBlockIdRoute
}

const ApiWebsitePagesKeyBlocksRouteChildren: ApiWebsitePagesKeyBlocksRouteChildren =
  {
    ApiWebsitePagesKeyBlocksBlockIdRoute: ApiWebsitePagesKeyBlocksBlockIdRoute,
  }

const ApiWebsitePagesKeyBlocksRouteWithChildren =
  ApiWebsitePagesKeyBlocksRoute._addFileChildren(
    ApiWebsitePagesKeyBlocksRouteChildren,
  )

interface ApiWebsitePagesKeyRouteChildren {
  ApiWebsitePagesKeyBlocksRoute: typeof ApiWebsitePagesKeyBlocksRouteWithChildren
  ApiWebsitePagesKeyPublishRoute: typeof ApiWebsitePagesKeyPublishRoute
  ApiWebsitePagesKeyUnpublishRoute: typeof ApiWebsitePagesKeyUnpublishRoute
  ApiWebsitePagesKeySectionsSectionTypeRoute: typeof ApiWebsitePagesKeySectionsSectionTypeRoute
}

const ApiWebsitePagesKeyRouteChildren: ApiWebsitePagesKeyRouteChildren = {
  ApiWebsitePagesKeyBlocksRoute: ApiWebsitePagesKeyBlocksRouteWithChildren,
  ApiWebsitePagesKeyPublishRoute: ApiWebsitePagesKeyPublishRoute,
  ApiWebsitePagesKeyUnpublishRoute: ApiWebsitePagesKeyUnpublishRoute,
  ApiWebsitePagesKeySectionsSectionTypeRoute:
    ApiWebsitePagesKeySectionsSectionTypeRoute,
}

const ApiWebsitePagesKeyRouteWithChildren =
  ApiWebsitePagesKeyRoute._addFileChildren(ApiWebsitePagesKeyRouteChildren)

interface ApiWebsitePagesRouteChildren {
  ApiWebsitePagesKeyRoute: typeof ApiWebsitePagesKeyRouteWithChildren
}

const ApiWebsitePagesRouteChildren: ApiWebsitePagesRouteChildren = {
  ApiWebsitePagesKeyRoute: ApiWebsitePagesKeyRouteWithChildren,
}

const ApiWebsitePagesRouteWithChildren = ApiWebsitePagesRoute._addFileChildren(
  ApiWebsitePagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OnboardRoute: OnboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  UserRoute: UserRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebsitePagesRoute: ApiWebsitePagesRouteWithChildren,
  ApiWebsitePageKeyRoute: ApiWebsitePageKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
