/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardLoginRouteImport } from './routes/_onboard/login'
import { Route as OnboardCreateAccountsRouteImport } from './routes/_onboard/create-accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OnboardActivateTokenRouteImport } from './routes/_onboard/activate.$token'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardLoginRoute = OnboardLoginRouteImport.update({
  id: '/_onboard/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardCreateAccountsRoute = OnboardCreateAccountsRouteImport.update({
  id: '/_onboard/create-accounts',
  path: '/create-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardActivateTokenRoute = OnboardActivateTokenRouteImport.update({
  id: '/_onboard/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-accounts': typeof OnboardCreateAccountsRoute
  '/login': typeof OnboardLoginRoute
  '/activate/$token': typeof OnboardActivateTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/create-accounts': typeof OnboardCreateAccountsRoute
  '/login': typeof OnboardLoginRoute
  '/activate/$token': typeof OnboardActivateTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/_onboard/create-accounts': typeof OnboardCreateAccountsRoute
  '/_onboard/login': typeof OnboardLoginRoute
  '/_onboard/activate/$token': typeof OnboardActivateTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/create-accounts'
    | '/login'
    | '/activate/$token'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/create-accounts'
    | '/login'
    | '/activate/$token'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/_onboard/create-accounts'
    | '/_onboard/login'
    | '/_onboard/activate/$token'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OnboardCreateAccountsRoute: typeof OnboardCreateAccountsRoute
  OnboardLoginRoute: typeof OnboardLoginRoute
  OnboardActivateTokenRoute: typeof OnboardActivateTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboard/login': {
      id: '/_onboard/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof OnboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboard/create-accounts': {
      id: '/_onboard/create-accounts'
      path: '/create-accounts'
      fullPath: '/create-accounts'
      preLoaderRoute: typeof OnboardCreateAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboard/activate/$token': {
      id: '/_onboard/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof OnboardActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OnboardCreateAccountsRoute: OnboardCreateAccountsRoute,
  OnboardLoginRoute: OnboardLoginRoute,
  OnboardActivateTokenRoute: OnboardActivateTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
